darwin/dataset/remote_dataset.py

Fixed bug on pulling annotation

Pytorch integration

---

darwin/client.py

Unauthenticated requests towards open datasets are now allowed

Client.default() now supported

---

README.md
darwin/client.py
darwin/torch/dataset.py
darwin/torch/utils.py

This PR fixes an issue with invalided polygons that have less than three points, discarding them from the annotations.

Discard polygons with less than three points

---

README.md
darwin/cli_functions.py
darwin/client.py
darwin/dataset/download_manager.py
darwin/dataset/remote_dataset.py
darwin/dataset/upload_manager.py
darwin/dataset/utils.py
darwin/torch/dataset.py
darwin/torch/utils.py
darwin/utils.py

Upload dataset now actually works (with multi thread support as well)

Upload dataset fix

---

darwin/cli_functions.py
darwin/client.py
darwin/config.py
darwin/dataset/download_manager.py
darwin/dataset/remote_dataset.py

new download design
+ no duplicate downloads
+ allow for subsets 
+ works on releases 
+ is fancy 
- no symlink used (yet)
Side effects: resume is no longer necessary and its integrated by design

New download

---

darwin/cli_functions.py
darwin/client.py
darwin/config.py
darwin/dataset/download_manager.py
darwin/dataset/identifier.py
darwin/dataset/release.py
darwin/dataset/remote_dataset.py
darwin/dataset/upload_manager.py
darwin/torch/dataset.py

Rebase of former update manager

New update manager

---

darwin/torch/dataset.py

This PR fixes a bug in the `InstanceSegmentation` class, adding back the loading of the list of classes.

add missing class loading

---

darwin/__init__.py
darwin/cli.py
darwin/cli_functions.py
darwin/client.py
darwin/dataset/__init__.py
darwin/dataset/download_manager.py
darwin/dataset/imports.py
darwin/dataset/remote_dataset.py
darwin/dataset/upload_manager.py
darwin/datatypes.py
darwin/exporter/__init__.py
darwin/exporter/exporter.py
darwin/exporter/formats/__init__.py
darwin/exporter/formats/coco.py
darwin/exporter/formats/pascalvoc.py
darwin/importer/__init__.py
darwin/importer/formats/__init__.py
darwin/importer/formats/csvtags.py
darwin/importer/formats/dataloop.py
darwin/importer/formats/pascalvoc.py
darwin/importer/importer.py
darwin/options.py
darwin/torch/dataset.py
darwin/torch/transforms.py
darwin/torch/utils.py
darwin/utils.py
setup.py

Import Annotations

---

darwin/exporter/exporter.py
darwin/exporter/formats/instance_mask.py
darwin/exporter/formats/semantic_mask.py
darwin/utils.py

This PR fixes an issue when exporting complex polygons and adds a grayscale mode (default mode now) for semantic masks.

Complex and grayscale masks

---

darwin/exporter/formats/__init__.py
darwin/torch/dataset.py
darwin/utils.py
docs/torch.md

This PR fixes a bug that occurs when coordinates are outside the image size.

Hotfix: clip coordinates to image size

---

darwin/cli.py
darwin/cli_functions.py
darwin/options.py

Before:
```
darwin dataset create mydataset --team myteam
```
After:
```
darwin dataset create myteam/mydataset
```

create datasets using full dataset identifier

---

darwin/dataset/remote_dataset.py

Get request have a query parameter length limitation.

Fetch item counts with post request

---

setup.py

Addresses https://github.com/v7labs/darwin-py/issues/144

Remove unused packages

---

darwin/cli_functions.py
darwin/client.py

- send darwin-py version as header
- fetch latest version

Check darwin-py version

---

darwin/cli_functions.py
darwin/client.py
darwin/config.py
darwin/dataset/remote_dataset.py
darwin/utils.py

Added some docs and typespecs. 
Fixed a possible crash when fetching remote classes.

Improving docs

---

darwin/dataset/upload_manager.py

Changed `max_workers` in upload manager to be `multiprocessing.cpu_counts()`

changed max_workers

---

darwin/dataset/remote_dataset.py

- support for creating annotations with sub types
- better error message

create annotation classes with sub annotations

---

darwin/dataset/remote_dataset.py

Documentation for new functionality regarding subannotation addition.

Documented code, added typespecs.

---

darwin/client.py
darwin/utils.py
tests/darwin/utils_test.py

- Added default path for darwin files
- Added tests for parse_darwin_json
- Added docs and typespecs

Add default path to import annotation

---

darwin/dataset/utils.py

- Added typespecs
- Added protection against crash if an invalid `split_type` is given.

Protection against invalid split type

---

darwin/__init__.py

version bump

---

darwin/cli_functions.py
darwin/client.py

Include progress when fetching dataset

---

darwin/importer/importer.py

Fix for issue:
https://github.com/v7labs/darwin-py/issues/267

added else block

---

darwin/importer/formats/labelbox.py
darwin/importer/formats/labelbox_schemas.py
tests/darwin/importer/formats/import_labelbox_test.py

Added polyline support for labelbox.
Testable with `pytest` as usual.

V7 2356 import polyline image

---

darwin/cli_functions.py

Adding Sphinx docs to this file.

Documented Public API of cli_functions.py

---

darwin/importer/formats/labelbox.py
darwin/importer/formats/labelbox_schemas.py
tests/darwin/importer/formats/import_labelbox_test.py

What?
-----
This PR aims to convert labelbox classifications into darwin.py annotation tags. 
Basically speaking, given an object with the following format:
```
{
"Label":{
"objects":[
{
"title": "SomeTitle",
"bbox":{"top":3558, "left":145, "height":623, "width":449}
},
{...}
],
"classifications": [
{
"value": "a_question",
"answer": {"value": "an_answer"}
},
....
]
},
"External ID": "demo-image-7.jpg"
},
{...}
```
We must be able to convert the `classifications` array into Annotation Tags.
-----
I have added tests so you can simply run `pytest` and everything should work.
Alternatively you can also do an import against a dataset you own:
```
darwin dataset import DATASET_NAME labelbox test.json
```
Where `test.json` is:
```
[
{
"Label": {
"objects": [
{
"title": …
```

V7 2357 import classifications as tags

---

darwin/__init__.py

- Added support for labelbox polygons, points and polylines (all images)
- Added support for labelbox classifications as darwinpy annotation tags
- Added tests for split datasets
- Added JSONschema validation for labelbox imports
- Documented Public API of cli_functions.py

version bump v0.7.2

---

darwin/config.py
darwin/datatypes.py
darwin/importer/formats/labelbox.py
darwin/torch/dataset.py

What?
------
- Added documentation to several classes and functions
- Fixed single backtick issue in other documentation files
- Attempting to fix labelbox docs
- Removed unused imports from dataset.py
What next?
-----------
Obviously this file is not yet fully documented, but I still want to merge it now because I feel this is growing too much. 
A review and merge now would make the next review easier.

Adding docs datatypes.py P1

---

darwin/dataset/utils.py
darwin/importer/formats/__init__.py
darwin/importer/formats/coco.py
darwin/importer/formats/csvtags.py
darwin/importer/formats/csvtagsvideo.py
darwin/importer/formats/darwin.py
darwin/importer/formats/dataloop.py
darwin/importer/formats/labelbox.py
darwin/importer/formats/pascalvoc.py
darwin/importer/formats/superannotate.py
darwin/importer/formats/superannotate_schemas.py
tests/darwin/importer/formats/import_labelbox_test.py
tests/darwin/importer/formats/import_pascalvoc_test.py
tests/darwin/importer/formats/import_superannotate_test.py

What?
------
- This handles the SuperAnnotate integration for Vector Points (they are the same as a `keypoint` in darwin)
- Changed the name `parse_file` to `parse_path` since sometimes we have to parse full datasets. 
- Removed validators from the function signature of labelbox
- Overall doc fixes
----------------
1. Create a folder with 2 files. One of the files must be called `classes.json`. The other can have any name you want.
2. In the file called `classes.json` write the following content:
```
[
{
{
"id": 1,
"name": "Sex",
{
"id": 1,
"name": "Male"
},
{
"id": 2,
}
],
},
{
"id": 2,
{
"id": …
```

Import Point Vector for SuperAnnotate

---

darwin/datatypes.py
darwin/importer/formats/labelbox_schemas.py
darwin/importer/formats/superannotate.py
darwin/importer/formats/superannotate_schemas.py
tests/darwin/importer/formats/import_superannotate_test.py

What
-------
Superannotate Vector Ellipse imports for darwin py.
How to test:
1. Create a JSON file with any name with the following format:
```
{
"instances": [
{
"type": "ellipse",
"classId": 2,
"cx": 922.1,
"cy": 475.8,
"rx": 205.4,
"ry": 275.7,
"angle": 0,
"groupId": 0,
"attributes": []
}
],
"tags": [],
"metadata": {
"version": "1.0.0",
"name": "sonnie-hiles-PUBt7UPbJFY-unsplash.jpg",
"status": "Completed"
}
}
```
And then add the following `classes.json` in the same folder:
```
[
{
{
"id": 1,
"name": "Sex",
{
"id": 1,
"name": "Male"
},
{
"id": 2,
}
],
},
{
"id": 2, …
```

Added Ellipse Vector import for superannotate

---

darwin/datatypes.py
darwin/importer/formats/superannotate.py
darwin/importer/formats/superannotate_schemas.py
tests/darwin/importer/formats/import_superannotate_test.py

What
------
Support to import SuperAnnotate Cuboid Vectors:
https://doc.superannotate.com/docs/vector-json#cuboid
How to test
---------------
1. create a folder to hold your files
2. inside that folder create a `classes.json` with the content:
```
[
{
{
"id": 1,
"name": "Sex",
{
"id": 1,
"name": "Male"
},
{
"id": 2,
}
],
},
{
"id": 2,
{
"id": 3,
"name": "Smiling"
},
{
"id": 4,
"name": "Sadness"
},
{
"id": 5,
"name": "Crying"
}
],
},
{
"id": 3,
"name": "Action",
{
"id": 6,
"name": "Skateboarding"
},
{
"id": 7,
"name": "Skating"
},
{
"id": 8, …
```

Added import support for SuperAnnotate cuboid vectors

---

darwin/datatypes.py
darwin/importer/formats/superannotate.py
darwin/importer/formats/superannotate_schemas.py
tests/darwin/importer/formats/import_superannotate_test.py

How to test
---------------
test.json:
```
{
"instances": [
{
"type": "polygon",
"classId": 2,
"points": [
1719.44,
1757.56,
1727.06,
1757.56,
1727.06,
1784.25,
1723.25,
1810.94,
1723.25,
1833.81,
1719.44,
1849.06,
1715.63,
1891.0,
1715.63,
1967.25,
1711.81,
2009.19,
1711.81,
2081.63,
1708.0,
2115.94,
1708.0,
2218.88,
1704.19,
2241.75,
1704.19,
2325.63,
1841.44,
2325.63,
1879.56,
2321.81,
2100.69,
2321.81,
2127.38,
2310.38,
2161.69,
2310.38,
2222.69,
2306.56,
2264.63,
2302.75,
2359.94,
2291.31,
2436.19,
2279.88,
3008.06,
2279.88,
3019.5,
2283.69,
3027.13,
2283.69,
3038.56,
2287.5,
3050.0,
2287.5,
3065.25,
2203.63,
3072.88,
2176.94,
3076.69,
2142.63,
3076.69,
2074.0,
3080.5,
2005.38,
3080.5,
1784.25,
3069.06,
1780.44,
3061.44,
1776.63,
3042.38,
1765.19,
3019.5,
1749.94, …
```

Adding import support for SuperAnnotate polygons

---

darwin/datatypes.py
darwin/importer/formats/superannotate.py
darwin/importer/formats/superannotate_schemas.py
tests/darwin/importer/formats/import_superannotate_test.py

test.json
```
{
"instances": [
{
"type": "polyline",
"classId": 2,
"points": [
1738.5,
1837.63,
1727.06,
2298.94,
3053.81,
2295.13,
3057.63,
1757.56,
1734.69,
1749.94
],
"groupId": 0,
"attributes": [],
"className": "Random"
}
],
"tags": [],
"metadata": {
"version": "1.0.0",
"name": "sonnie-hiles-PUBt7UPbJFY-unsplash.jpg",
"status": "Completed"
}
}
```
classes.json
```
[
{
{
"id": 1,
"name": "Sex",
{
"id": 1,
"name": "Male"
},
{
"id": 2,
}
],
},
{
"id": 2,
{
"id": 3,
"name": "Smiling"
},
{
"id": 4,
"name": "Sadness"
},
{
"id": 5,
"name": …
```

Addded polyline import support for SuperAnnotate

---

setup.py

Remove requests_toolbelt dependency

---

darwin/dataset/split_manager.py
tests/darwin/dataset/split_manager_test.py

[Refactor] Split Management

---

darwin/dataset/remote_dataset.py
darwin/importer/formats/pascal_voc.py

Some of the code blocks in the documentation were malformated. 
This PR fixes them.

Fixed inline code-blocks

---

darwin/exporter/formats/coco.py
darwin/exporter/formats/dataloop.py
darwin/exporter/formats/numpy_encoder.py
tests/darwin/exporter/formats/export_coco_test.py

NOTE
------
I have deprecated most of the file, because most of it were simply private functions in reality. Not being used anywhere else. 
Reduction of the public API is something I usually aim for when possible.

V7 2246 darwin/exporter/formats/coco.py

---

darwin/dataset/remote_dataset.py
tests/darwin/dataset/remote_dataset_test.py

Addressing issue with: https://github.com/v7labs/darwin-py/issues/357

fixing failure to fetch files with commas

---

darwin/cli_functions.py

Its about time.
```
$ darwin dataset files cars
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                                                 ┃ Status   ┃ URL                                                      ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ ferrari-laferrari.jpg                                │ review   │ https://staging.v7labs.com/workview?dataset=312&image=34 │
│ alan-king-1R63taCoSnM-unsplash.jpg                   │ complete │ https://staging.v7labs.com/workview?dataset=312&image=2  │
│ campbell-3ZUsNJhi_Ik-unsplash.jpg                    │ annotate │ …
```

Listing files now prints a rich table.

---

darwin/options.py

Fixing incorrect help message for `darwin convert -h`

fixing typo

---

darwin/importer/importer.py

Platform now allows same class name with different main type; revert checking

---

darwin/backend_v2.py
darwin/cli_functions.py
darwin/dataset/remote_dataset.py
darwin/dataset/remote_dataset_v1.py
darwin/dataset/remote_dataset_v2.py
darwin/item.py
tests/darwin/dataset/remote_dataset_test.py

Refactors out post_comments from cli_functions to remotedataset,
Adds a new implementation for v2 datasets.

[V7-3306] 2.0 Comment support

---

darwin/client.py

The num_video field is no longer supplied when creating a dataset, made it optional.

[Bug] Dataset Creation fix

---

darwin/exporter/formats/__init__.py
darwin/exporter/formats/yolo.py
tests/darwin/exporter/formats/export_pascalvoc_test.py
tests/darwin/exporter/formats/export_yolo_test.py

[Source](https://towardsdatascience.com/image-data-labelling-and-annotation-everything-you-need-to-know-86ede6c684b1)

[ANN-133][internal] Export to YOLO format

---

darwin/dataset/upload_manager.py

Fixes issue on:
https://linear.app/v7labs/issue/SWAT-444/[bug]-files-are-stuck-in-uploading-when-uploading-them-to-a-folder-via

[SWAT-444][External] Added missing path to item

---

darwin/cli_functions.py
darwin/exceptions.py
darwin/importer/formats/coco.py

Application crashes when file has cyrilic characters. This PR aims to fix that. 
SWAT: https://linear.app/v7labs/issue/SWAT-464/coco-annotation-import-with-cyrillic-characters-fails-for-innodata

[SWAT-464][External] Added several decoding algorithms to try when opening files

---

.github/workflows/document.yml

Adds `medical` to pip install command to have docs work.
Can confirm it fixes Documentation workflow 👍

updated dependency to include medical

---

darwin/dataset/download_manager.py
darwin/exporter/formats/darwin_1_0.py

See: https://linear.app/v7labs/issue/IO-461/request-darwin-dataset-pull-command-with-video-frames-option-downloads

[IO-461][external] Convert RG16 images into grayscale

---

darwin/utils.py
tests/darwin/utils/find_files_test.py

Code on master was not reading directories, only files.  This fixes that, and adds unit tests to avoid it in future.

IO-575: Issue with directory imports

---

.github/workflows/tests.yml

Fix to make the builds work again, after a change to github actions today.

Fix for windows builds

---

docs/README.md
docs/release_process.md

Updates to docs, at request of @sardaukar  and @rslota.

Updating docs for release process

---

.github/workflows/document.yml
poetry.lock
pyproject.toml

* Version bump
* Change to documentation build

Version_bump_v0.8.9

---

darwin/dataset/remote_dataset.py
darwin/dataset/remote_dataset_v1.py
darwin/dataset/remote_dataset_v2.py

Changes List -> Sequence for function calls for correct mypy type inference

Io 585 incorrect type annotation

---

darwin/client.py
darwin/dataset/remote_dataset.py
darwin/dataset/remote_dataset_v2.py
tests/darwin/dataset/remote_dataset_test.py

Added release to the dataset object. Using get_remote_dataset with a string containing a release (ie 'v7-labs/random-image:testexport1')will set the release and download that rather than latest.

including release in dataset

---

darwin/importer/importer.py
tests/darwin/importer/importer_test.py

Revert "[IO-835][external] Fix for a logic flow bug in importer"

---

README.md

[io-686][internal] Correct link in readme

---

darwin/exporter/formats/mask.py
tests/darwin/exporter/formats/export_mask_test.py

@rslota encountered an issue with polygon rendering, this fixes it.

[IO-1008][internal] Polygon rendering fix

---

darwin/cli.py
darwin/exceptions.py
darwin/exporter/formats/mask.py

Fix for bug in IO-1076, inconsistent palette generation in code.

[IO-1076][internal] Fix for palette generation across multiple file sets

---

darwin/future/core/client.py
darwin/future/meta/client.py
darwin/future/tests/meta/test_client.py
test.py

Creation of meta api client object for use with higher level and user centric interaction with darwin objects
Introduction of MetaClient object and associated functionality

[Io-759] Meta Api Client

---

darwin/exporter/formats/nifti.py

Current version of this in prod is failing leading to bad Exports hanging instead of failing gracefully - Error message creation is broken here due to an extra argument. This is a hotfix but we should add unit tests for this functionality.
Fixed bug associated with bad export error message creation

[MED-235][external] removed slot from argument to fix error message issue

---

.github/workflows/e2e.yml

Slack code was tested for github actions and needs to be removed
remove extra slack code
Slack notifier added to e2e testing suite

[IO-1349] Setting up slack notifications for failed e2e tests

---

.github/workflows/EVENT_merge_to_master.yml
.github/workflows/JOB_check-master-can-release.yml

Revert "Bump actions/github-script from 3 to 7"

---

darwin/datatypes.py
darwin/importer/formats/nifti.py
darwin/utils/utils.py
tests/darwin/exporter/formats/export_mask_test.py

The Darwin backend makes use of two functions that were previously removed from darwin-py
Re-add those functions
Re-added functions used by the Darwin backend

[DAR-1734][External] Re-add functions used by the backend

---

darwin/dataset/local_dataset.py
darwin/dataset/utils.py

- A sometimes unclear missing image error message & missing type hints
- Added missing type hints
- Improved missing image error by displaying the path to where the missing file should have been
- Improved type hints & missing image error message

[DAR-2240][External] Typing improvements & better missing image error message

---

tests/darwin/importer/importer_test.py

The main import function, `import_annotations()` was lacking some unit tests. Several unwritten placeholders were present
This PR populates those placeholder tests
Improved test coverage of annotation import flow

[DAR-2785][External] Improved test coverage of `import_annotations()`

---

README.md

Add scorecard badge to README

---

darwin/exporter/formats/nifti.py
tests/darwin/exporter/formats/export_nifti_test.py

When exporting `NifTI` annotations, darwin-py uses the exported `mask_annotation_ids_mapping` to create a mapping of annotation IDs to integer values. These are used to create 1 mask per annotation class
The problem is that the exporter makes the assumption that this mapping is unique among all frames. This is not the case. For example, imagine a case with 3 mask classes and 2 frames. On frame 1, I have mask class 1. On frame 2, I have mask classes 2 & 3, but not mask class 1. In the export, we get something like this:
```
"frames": {
"0": {
"keyframe": true,
"raster_layer": {
"dense_rle": []
"mask_annotation_ids_mapping": {
"8ab247a8-e032-4332-8834-ba5b3e5badf0": 1
},
"total_pixels": 2073600
}
},
"1": {
"keyframe": true,
"raster_layer": {
"dense_rle": []
"mask_annotation_ids_mapping": { …
```

[DAR-5976][Externla] Globally frame-unique mask annotation ID mapping
