- darwin/dataset.py
This PR adds a new parameter in the `dataset.pull()` method called `image_status` that can be used to filter the images that are gonna be downloaded by their current status in Darwin (eg. "done" or "in review").
For example, `dataset.pull(image_status="done")` will download only those images that have been annotated and reviewed.
> dataset.pull(): add filter by image_status

- README.md
- darwin/cli_functions.py
- darwin/dataset/remote_dataset.py
- setup.py
`RemoteDataset.pull()` now matches the functionality of the CLI.
The optional parameters `blocking` and `multi_threaded` allow to either get the iterator or use a single thread to download the data.
> Download dataset

- darwin/torch/dataset.py
Resolved the issue of hitting the FS N times (with glob) for loading the data.
This solution is very fast instead; the drawback is that we lose the error message if the image is present with multiple extensions (which is not allowed by darwin anyway) and instead roll with the "last" one we find.
> fixed the slow loading of image paths

- darwin/torch/dataset.py
The dataloader now returns the file name as well; this will be useful to visualize/make statistics about failure or successful images and it is backward compatible with previous versions.
> Dataloader and filename

- darwin/torch/__init__.py
- darwin/torch/dataset.py
- darwin/torch/transforms.py
This PR adds an option to disable the polygon to mask conversion in segmentation datasets. It also splits the `get_height_and_width` function into two, adding as a results a new function `get_img_info`, and fixes a couple of bugs.
> Toggle polygon to mask conversion

- darwin/dataset/utils.py
This PR fixes a bug with float and numpy indices in the function `split_dataset` in `dataset/utils.py`.
> Bug fix: float indices in dataset split

- darwin/dataset/utils.py
This PR introduces the concept of default splits for Darwin datasets, and adds a flag to make a given split the default one. The default split will be always located under `DB_ROOT/lists/split` in the local copy of the dataset.
> New feature: default split

- darwin/dataset/utils.py
- darwin/torch/README.md
- darwin/torch/__init__.py
- darwin/torch/dataset.py
- darwin/utils.py
Restores `get_dataset()` function in the `darwin.torch` toolbox.
```
from darwin.torch import get_dataset
get_dataset("/PATH/TO/YOUR/DATASET", DATASET_TYPE [, PARTITION, SPLIT_TYPE, RELEASE_NAME, TRANSFORMS])
```
> Restores get_dataset() function in the darwin.torch toolbox

- darwin/exporter/formats/cvat.py
cvat export timestamps should include the timezone. See [XML 1.1 Annotation](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/xml_format.md) format
> cvat export includes timezone

- darwin/torch/__init__.py
Removing `pycocotools` dependency since we don't use it anymore to generate masks.
> Remove pycocotools dependency

- setup.py
Using darwin-py with python 3.6 results in the following error during installation of requirements:
requirements.txt:
<snip>
darwin-py==0.5.14
<snip>
` Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-w562jode/darwin-py_19665130c7244b609fa181f78ad2f4ea/setup.py", line 4, in <module>
long_description = f.read()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3193: ordinal not in range(128)`
The problem is some kind of UTF-8 symbol in the readme.
This pull request fixes the issue, by decoding as UTF-8.
> Fix unicode decoding problems during package installation for python 3.6

- darwin/importer/formats/pascalvoc.py
- darwin/importer/importer.py
- setup.py
- tests/darwin/importer/formats/pascalvoc_test.py
Addresses https://github.com/v7labs/darwin-py/issues/137
> [HOTFIX] Pascalvoc importer should not fail on float values

- .gitignore
- setup.cfg
- setup.py
Read the version number directly from `./darwin/__init__.py` avoiding to load darwin before the required dependencies are installed. 
Moreover, I've added the classic [`.gitignore`](https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore) entries in ours.
> Import free version number in config.py + gitignore

- darwin/importer/importer.py
https://vseven.slack.com/archives/C01P1V6JZ1P/p1631527813109900
Based on a customer not invoking the clearly documented API correctly, we decided to throw an error when the API contract was not being respected.
> added type_check for path

- .vscode/settings.json
- source/_static/js/custom.js
- source/conf.py
- source/index.rst
What
----
Added hack to automatically expand left menu Packages list when opening a page.
Why
----
We agreed on a meeting that it would be more convenient and explicit for our users to have the list of package and subpackages expanded automatically upon opening the page. 
How
----
In a rather surprising twist, the option to have the left menu bar expanded is bugged and DOES NOT WORK. 
I had to resort to hacking the crap out of the DOM to make it happen. I tried making the code readable. Sorry for the suffering caused to any reviewers/victims.
----
1. Download branch
2. Install dependencies
3. Run `rm -f README.rst && m2r README.md && mv README.rst source/ && rm -rf docs/*  && sphinx-apidoc -f -o source darwin && sphinx-build -b html source/ docs/`
4. Go to …
> added hack to expand left menu sidebar

- darwin/importer/formats/pascalvoc.py
- tests/darwin/importer/formats/pascalvoc_test.py
Why
----
Upon reviewing the code for `pascal_voc` files I realized that the `<filename></filename>` child element could be empty or simply contain a `' '` space. 
I fixed this issue to avoid future problems. 
-----------------------------
Since I added a test, running `pytest` should do it.
> fixed check on filename not existing

- darwin/importer/formats/pascalvoc.py
Why
----
One of our users is having trouble importing a `pascalvoc` file. Upon further analysis, I concluded his file did not have the format we expected to find.
What
---
I have asked the client to change the format of his `pascalvoc` file. However I also understand the format we expected was not documented at all. 
I documented the expected format.
> improved docs

- darwin/exporter/formats/pascalvoc.py
- tests/darwin/exporter/formats/export_pascalvoc_test.py
Slack link: https://vseven.slack.com/archives/CJUN8TRJA/p1636468559125000
When exporting to PascalVOC format, the bounding boxes of Polygons are being discarded. 
This PR fixes that.
> added support for polygon and complex_polygon bboxes

- darwin/cli.py
- darwin/cli_functions.py
- darwin/client.py
- darwin/dataset/remote_dataset.py
- darwin/options.py
- tests/darwin/cli_functions_test.py
- tests/darwin/dataset/remote_dataset_test.py
We don't support file deletion from the CLI
Add argument parser option and functions, which are pretty similar to the ones for setting an item status.
Note: this PR is changing `delete` APIs, and is not retro-compatible. With that said, the new API is aligned to `post` and `put`, which I think is important.
Because of the aforementioned reasons, I would release a new minor version: `0.7.0`
> [V7-2192] Allow for item deletion in CLI

- darwin/datatypes.py
- tests/darwin/datatypes_test.py
Background
----
Coco imports were failing for one of our customers. 
The fix was to add default types to `make_polygon` and `make_complex_polygon`.
How can I test
-----
Tested locally with script and command line. 
Coco file used:
[21-11-03_15-24-02_coco.zip](https://github.com/v7labs/darwin-py/files/7562979/21-11-03_15-24-02_coco.zip)
You can use something simillar:
```
darwin dataset import andreas-team/cars coco 21-11-03_15-24-02_coco.json
Fetching remote class list...
Retrieving local annotations ...
Fetching remote file list...
1 annotation file(s) found.
1 classes needs to be created.
0 classes needs to be added to andreas-team/cars
About to create the following classes
plants, type: polygon
Do you want to continue? [y/N] y
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% …
```
> Added default values to optional types

- darwin/dataset/remote_dataset.py
- darwin/dataset/split_manager.py
Background
----
A user reported in Github that `dataset.split` was not working. 
This PR aims to fix this issue. 
How can I test this
------
You can use this code snippet to run the code:
```
from darwin.client import Client
client = Client.local()
dataset = client.get_remote_dataset("cars")
dataset.pull()
dataset.split()
```
> Fix bug with dataset split in darwin-py

- darwin/importer/formats/labelbox.py
- tests/darwin/importer/formats/import_labelbox_test.py
Background
-----
Added LabelBox Polygon Image support for importations.
- https://docs.labelbox.com/docs/polygon-json
- Improved error messages
- Updated docs for public API
- Added more tests
Note
----
I am not generating the polygon's bounding box out of the Polygon data. If this is required, let me know!
-----------
Use the following `test.json` as a guide.
If you have a dataset, pick an image (any image) and replace the `External ID` field with your image's name:
```
[
{
"Label": {
"objects": [
{
"title": "UglyCar",
"polygon": [
{"x": 3665.814, "y": 351.628},
{"x": 3762.93, "y": 810.419},
{"x": 3665.814, "y": 351.628}
]
}
]
},
"External ID": "serge-kutuzov-1K9-TbJWs2U-unsplash.jpg"
}
]
```
Then you can import this dummy annotation into your dataset with the …
> Adding support for polygons

- darwin/importer/formats/__init__.py
- darwin/importer/formats/labelbox.py
- darwin/importer/formats/labelbox_schemas.py
- setup.py
- tests/darwin/importer/formats/import_labelbox_test.py
Background
----
I have, for the first time in darwin-py's life, added JSON schema validation, this time to Labelbox. 
However, there are a couple of things I am not a big fan of:
- The error message for `oneOf` is simply wrong. It says `"point" is required` which is not true, `point` is only one of the possible valued (bbox and polygon being the others).
- After double checking, I have realized `jsonschema` is only compatible with Python 3.7 and onwards. I have to use an alternative. 
In the meantime I would like a review of the code. What do you guys think?
----
Simply run `pytest`.
EDIT
----
Replaced `jsonschema` with `jsonschmea_rs` because the second one is the only one compatible with all the versions of Python `darwin-py` official supports. 
Although the issue …
> added JSONschema validation to labelbox

- darwin/importer/formats/labelbox.py
- tests/darwin/importer/formats/import_labelbox_test.py
What changed
-----
Added support for labelbox Point. 
The schema was already here, so I didnt have to add it.
How can I test it?
----
with `pytest`, as a new test was added !
> Adding support for labelbox Point

- .github/workflows/document.yml
What is happening?
------
Document generation is currently failing. This is happening because one of the dependencies used to generate the docs ( m2r ) is crashing due to a dependency management conflict (in this case mistune did a backwards incompatible release and m2r is using it because their creator doesn't believe in locked versions ... ). 
To fix this (somewhat temporarily) I have added mistune manually to the pipeline with a locked version. This fixes the issue, until the creator of m2r does a full refactoring of m2r to be compatible with mistune, or until he accepts the value of locking versions in dependency trees.
Not the easiest issue to find.
> Fix docs GitHub flow

- darwin/importer/formats/labelbox.py
We cannot display code blocks like in markdown.
The parser translates them to a sort of Italic:
https://darwin-py-sdk.v7labs.com/darwin.html#module-darwin.config
While it is clearly not code, it is passable. We could use double backtick and go for monospace.
I don't like it, but I could live with it if only it didn't create messes like this:
https://darwin-py-sdk.v7labs.com/darwin.importer.formats.html#module-darwin.importer.formats.labelbox
This PR tries to fix that.
> fixing code blocks

- darwin/importer/formats/superannotate.py
- darwin/importer/formats/superannotate_schemas.py
- tests/darwin/importer/formats/import_superannotate_test.py
How to test
----------
JSON test file:
```
{
"instances": [
{
"type": "bbox",
"classId": 2,
"points": {
"x1": 1727.06,
"x2": 3057.62,
"y1": 1723.25,
"y2": 2295.13
},
"groupId": 1,
{
"id": 11,
"groupId": 4
}
]
}
],
"tags": [],
"metadata": {
"version": "1.0.0",
"name": "sonnie-hiles-PUBt7UPbJFY-unsplash.jpg",
"status": "Completed"
}
}
```
classes.json file:
```
[
{
{
"id": 1,
"name": "Sex",
{
"id": 1,
"name": "Male"
},
{
"id": 2,
}
],
},
{
"id": 2,
{
"id": 3,
"name": "Smiling"
},
{
"id": 4,
"name": "Sadness"
},
{
"id": 5,
"name": …
```
> Adding support for superannotate bbox import

- darwin/importer/formats/superannotate.py
- tests/darwin/importer/formats/import_superannotate_test.py
Background
--------
With  SuperAnnotate you can have a class name being used for multiple types. 
Example: you have a cat class, and you can create polygon , bounding_box or ellipse annotations with it
This PR adds the SuperAnnotate type to the end of the class name, this way we will be able to support this feature because for Darwin these will be different Annotations: `cat-polygon, cat-bounding_box and cat-ellipse`
> added superannotate types to class name

- darwin/datatypes.py
- darwin/importer/formats/superannotate.py
- darwin/importer/formats/superannotate_schemas.py
- darwin/importer/importer.py
- tests/darwin/importer/formats/import_pascalvoc_test.py
- tests/darwin/importer/formats/import_superannotate_test.py
Background
---------------
This PR adds attribute import support for superannotate attributes.
How can  I test?
-------------
Before testing there is one important detail: **The attributes will only be imported if they already exist**. Because for this condition to be true, the AnnotationClass must already exist and have the attributes defined, this means that if you are importing a new class, the class import will work, but it won't have any attributes.
A print message was added to give visibility to this issue.
**test.json**
```
{
"instances": [
{
"type": "bbox",
"classId": 2,
"points": {
"x1": 275.4,
"x2": 570.3,
"y1": 590.8,
"y2": 1440
},
"groupId": 0,
{
"id": 2,
"groupId": 1
},
{
"id": 3, …
```
> V7 2629 support attributes

- darwin/importer/formats/superannotate.py
- darwin/importer/formats/superannotate_schemas.py
- tests/darwin/importer/formats/import_labelbox_test.py
- tests/darwin/importer/formats/import_superannotate_test.py
What
----
This PR adds support for SuperAnnotate tags. It should be the last  step needed to complete the SuperAnnotate import project (aside from rotated bounding boxes which are on ice for the time being).
It also adds some additional checks to the superannotate_schema that were missing from the last PR.
How to test
--------------
**test.json**
```
{
"instances": [
{
"type": "bbox",
"classId": 2,
"points": {
"x1": 275.4,
"x2": 570.3,
"y1": 590.8,
"y2": 1440
},
"groupId": 0,
{
"id": 2,
"groupId": 1
},
{
"id": 3,
"groupId": 2
}
]
}
],
"tags": [
"orange",
"red"
],
"metadata": {
"version": "1.0.0",
"name": "sonnie-hiles-PUBt7UPbJFY-unsplash.jpg",
"status": "Completed"
}
}
```
**classes.json**
```
[
{ …
```
> Added support for superannotate tags

- darwin/cli.py
- darwin/cli_functions.py
- darwin/client.py
- darwin/options.py
- tests/darwin/client_test.py
What ?
-------
A client of ours added this functionality a while ago to their version of darwin-py and then they got mad when they updated to the newest version and realized their changes to the cloned project were gone ( go figure ! )
This PR adds the functionality of adding a comment to a file via CLI and SDK.
How to test it?
----------
Pick a dataset and a file and use the following command:
(all the args passed with `--` are OPTIONAL, meaning you only have to pass the dataset slug, filename and the text_comment):
```
dataset comment {DATASET_SLUG} {FILENAME} --text {TEXT_COMMENT} --x {X} --y {Y} --w {WIDTH} --h {HEIGHT}
```
You should then see a comment box with your comment on the image.
> Add comments to items in datasets 

- darwin/client.py
- tests/darwin/client_test.py
Bug found while solving this ticket:
https://linear.app/v7labs/issue/V7-2832/http-422-error-in-python-sdk-for-bgn
> [HOTFIX] Fixing a bug where response headers are not being correctly identified

- darwin/cli.py
- darwin/cli_functions.py
- darwin/importer/importer.py
- darwin/options.py
- tests/darwin/cli_functions_test.py
Allows for 
```sh
darwin dataset import --yes my-dataset darwin.json
```
And 
```python
import_annotations(dataset, parser, files, append, class_prompt=False)
```
to skip the `secure_continue_request` prompts.
> Addes --yes flag to skip prompts when importing

- darwin/importer/importer.py
This is likely to change soon ... and will then require re-updating and releasing darwin-py.
https://www.notion.so/v7labs/Allow-Same-Name-classes-of-different-Types-424578ba84a14c118101ccd3ed29366f
But in the meantime; could it be worth giving a friendly; informative helpful message to the end user?
```
Fetching remote class list...
Retrieving local annotations ...
Fetching remote file list...
1 annotation file(s) found.
`one` class of type `bounding_box` from imported annotations clashes with an existing class of the same name; but of type `tag`
`Surface damage` class of type `keypoint` from imported annotations clashes with an existing class of the same name; but of type `bounding_box`
Class names must be unique; even across types (see above error); can not proceed with import.
```
> Detect if new class will clash with existing class of different type.

- darwin/exporter/formats/__init__.py
- darwin/importer/formats/__init__.py
After a discussion with Brent, we decided to add this not here, because this information is not reflected anywhere else.
> Added note to update docs

- darwin/cli_functions.py
- darwin/dataset/remote_dataset.py
- darwin/options.py
The command `darwin dataset export cars lights_v3 "1439 1438"` was not working. 
Basically the function expected a list of strings, and we were always passing a string no matter what. The resulted in bad requests to the backend. 
This PR fixes that. Now before making the HTTP call, I split the string into a list. 
I also updated the docs accordingly.
> fixed dataset export not working with class ids

- darwin/options.py
Right now if we run `-h` we see this:
```
darwin dataset split -h
usage: darwin dataset split [-h] -v VAL_PERCENTAGE [-t TEST_PERCENTAGE] [-s SEED] dataset
positional arguments:
dataset               Local dataset name to split.
optional arguments:
-h, --help            show this help message and exit
-v VAL_PERCENTAGE, --val-percentage VAL_PERCENTAGE
Validation percentage.
-t TEST_PERCENTAGE, --test-percentage TEST_PERCENTAGE
Test percentage.
-s SEED, --seed SEED  Split seed.
```
Which is incorrect, because if we try to run `darwin dataset split planes` the action will fail. Both `val-percentage` and `test-percentage` are actually mandatory. 
This PR fixes that:
```
$ darwin dataset split -h
usage: darwin dataset split [-h] [-s SEED] dataset val-percentage test-percentage
positional …
```
> fixed val-percentage and test-percentage being optional

- darwin/cli.py
- darwin/cli_functions.py
- darwin/dataset/remote_dataset.py
- darwin/options.py
Fixing `annotation_class_ids` being mandatory an not optional. Now help menu shows:
```
$ darwin dataset export -h
usage: darwin dataset export [-h] [--class-ids CLASS_IDS] [--include-authorship] [--include-url-token] dataset name
positional arguments:
dataset               Remote dataset name to export.
name                  Name with with the version gets tagged.
optional arguments:
-h, --help            show this help message and exit
--class-ids CLASS_IDS
List of annotation class ids. If present, it will only include items that have annotations with a class whose id matches.
--include-authorship  Each annotation contains annotator and reviewer authorship metadata.
--include-url-token   Each annotation file includes a url with an access token.Warning, anyone with the url can access the …
```
> Make class IDs list optional when generating a new dataset export

- darwin/cli_functions.py
- darwin/client.py
- darwin/datatypes.py
- tests/darwin/cli_functions_test.py
Now instead of always saying "Files deleted successfully!", it prints files that were not found and prints the result of the overall operation:
```
$ darwin dataset delete-files helis asdf dajsdnad asjdd
Do you want to continue? [y/N] y
File not found: asjdd
File not found: asdf
File not found: dajsdnad
Operation successfully completed!
```
Related to:
https://github.com/v7labs/darwin-py/issues/381
> Delete non existent files

- darwin/importer/formats/coco.py
Right now, `coco` imports for polygons are broken. 
This PR fixes that.
> [SWAT-48] fixing coco imports not working

- setup.py
From what I can tell, `darwin` isn't importable on Ubuntu 18 with Python 3.10. However, the issue is in upolygon 0.1.6 and not in darwin-py.
Partial stacktrace:
```
File "/home/jolae/miniconda3/envs/downloader_3_10/lib/python3.10/site-packages/darwin/utils.py", line 24, in <module>
from upolygon import draw_polygon
File "/home/jolae/miniconda3/envs/downloader_3_10/lib/python3.10/site-packages/upolygon/__init__.py", line 1, in <module>
from draw_polygon import draw_polygon  # noqa
ImportError: /home/jolae/miniconda3/envs/downloader_3_10/lib/python3.10/site-packages/draw_polygon.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```
Indeed, `upolygon` version 0.1.6 isn't importable. I upgraded to `upolygon==0.1.8` locally, and then I see no issues with either darwin nor …
> Update to upolygon 0.1.8

- setup.py
According to https://pypi.org/project/dataclasses/ in Python>=3.7 the built-in module should be used instead.
This was causing issues for us on Python3.8 where the darwin dataclasses dependency was causing issues by using the PyPi module not the built-in one which is incompatible.
> Fix dataclasses dependency for Python>=3.7

- darwin/dataset/download_manager.py
This PR adds ability to download multiple files when they are registered as single file with multiple keys.
Related PR in darwin-backend - https://github.com/v7labs/darwin-backend/pull/2352
Swat issue - https://linear.app/v7labs/issue/SWAT-394/client-gets-python-error-when-uses-darwin-dataset-pull-command
> [SWAT-394][internal] Handle multi-file dicom downloading

- darwin/cli.py
- darwin/cli_functions.py
- darwin/exceptions.py
- darwin/importer/importer.py
- darwin/item.py
- darwin/options.py
- Fixes crash when importing an annotations file that has no annotations
- Revamped the print messages to use Rich instead of `print` (consistency changes).
Ticket: https://linear.app/v7labs/issue/SWAT-450/regression-error-when-importing-empty-annotation-files
> [SWAT-450][External] Skipping import of file if no annotations are present

- darwin/dataset/remote_dataset.py
- darwin/dataset/remote_dataset_v1.py
- darwin/dataset/remote_dataset_v2.py
- darwin/dataset/upload_manager.py
Hello,
This is for [issue #427 ](https://github.com/v7labs/darwin-py/issues/427).
Now, the value of `max_workers`, can be passed from `RemoteDataset` objects directly into `UploadHandler`. Additionally, there are some validation that is done on `max_workers` in `UploadHandler`.
> Pass number of max workers for upload

- darwin/client.py
Hello,
It was a fix for a bug with dataset create in RemoteDatasetV2 [here](https://github.com/v7labs/darwin-py/commit/7bebe08a4e416ddfb0aee70d3de2e9e5176d887e). However, the issue still persists with RemoteDatasetV1.
This fix is about to solve it.
> Fix the dataset create bug where num_videos could be missing in RemoteDatasetV1

- darwin/dataset/download_manager.py
- darwin/dataset/remote_dataset.py
- darwin/dataset/utils.py
This PR makes it so downloading frames is counted in progress bar and uses multi-threading, significantly speeding up single items pulls. 
This also adds `DARWIN_DOWNLOAD_FILES_CONCURRENCY` variable to allow for fine tuning this concurrency.
> [IO-432][external] Pull video frames concurrently

- setup.py
`sklearn` has been deprecated as a way of pip installing `scikit-learn` which makes our master build fail - see  https://pypi.org/project/sklearn/ for more details
> fixed deprecated dependency

- darwin/utils.py
Take `original_filename` as filename, if not available, fallback to `filename`
> [SWAT-605] [External] Darwin rename file format .JPG to .jpg when exporting

- .github/workflows/tests.yml
PRs are failing because github python available versions changed
> Change to Py versions

- darwin/dataset/remote_dataset.py
Export ZIP deals with this issue by adding `_N` suffix in case of name conflict, but darwin-py doesn't do anything like that right now, which leads to files being overridden if we have items with same name, but different `path`.
> [IO-483][external] Fix dataset pull with non-unique item names

- setup.py
locking numpy version as updates do not following semantic versioning and are not backwards compatible.
> [SWAT-702][Internal] Locked numpy version

- darwin/torch/dataset.py
If an annotation has `paths` and not `path` (eg `complex_polygon`), the `SemanticSegmentationDataset` will raise a `KeyError` exception. This fix iterates through all paths and appends each sequence to the annotations.
> Fix bug that raises KeyError exception for complex_polygon

- darwin/torch/transforms.py
The current transforms do not work for `SemanticMasks` which has `mask` and not `masks`. This is a minimal change that fixes the issue for the flip transforms.
> Fix transform bugs for SemanticMask by checking for "mask" or "masks".

- darwin/dataset/split_manager.py
The current logic does not take into account files that may have `.json` in the middle of the file name. The change ensure that the split happens only for the last `.json` occurrence
> [SWAT-716][internal]: Fix .json extension parsing for dataset splitting

- darwin/torch/dataset.py
This makes it possible to use this function without setting an environment variable or creating a config file. Currently, calling the function without the environment variable or config file results in an obscure message followed by "Error: Authenticate first" https://github.com/v7labs/darwin-py/blob/1abb2595da0555aef88b589e04d7d2eee2edcf3e/darwin/cli_functions.py#L1242.
> Allow passing a Client to get_dataset()

- darwin/exporter/formats/__init__.py
We are missing nifti in error message of supported formats:
```
$ darwin convert asd /home/pedro/Downloads/v7-support-test-1675683152 /home/pedro/Downloads/output 
asd
Error: Unsupported export format, currently supported: ['coco', 'cvat', 'dataloop', 'darwin_1.0', 'instance_mask', 'pascalvoc', 'semantic_mask', 'semantic_mask_grey', 'semantic_mask_index', 'yolo']
```
Add nifti to list
> [SWAT-735][internal] Added nifti to supported formats.

- darwin/exporter/formats/mask.py
Files that have duplicate names in different folders would not correctly convert as the directory path was not taken into account when computing the destination file name. This change ensures that we include the full darwin file path instead of just the file name.
> [SWAT-753][external]: Fix 'darwin convert' to mask formats path issue

- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
Changes that allow `darwin-py` to install with PIP on python 3.7.x versions.
Whilst installation on Python 3.7.x and below can be problematic, we have some users who do still use this, and this change will allow them to install more easily in pipelines.
Changed required Python versions from `<=3.8, <3.11` to `<=3.7, <=3.11`.  Allowing install on both 3.7 and 3.11 in untested versions.
Added pipeline step that attempts to install the pip package on 3.7 and 3.11 for both windows and ubuntu
Added constraints to prevent incompatible versions installing.
Relocked poetry versions
> [IO-749][external] Added python support install on 3.7

- darwin/datatypes.py
- darwin/utils.py
- tests/darwin/utils_test.py
These fields are present in the darwin JSON v2 export, but they are not exposed by the relevant python types.
We need these for some upcoming work which reads darwin-py exports.
> [MOD-603][external] Add annotation file item_id and annotation id.

- darwin/torch/dataset.py
- darwin/torch/transforms.py
- tests/darwin/torch/dataset_test.py
A fix to overcome the underlying issue of background class in a  semantic segmentation datasets being mixed in with the first user generated class. Background classes were not present in the SemanticSegmentationDataset but was intendid behaviour. Background class now gets added to the class if not present, and class functions that call on class features like compute_weights have been updated to reflect the underlying background class, which is treated differently because it's not a user defined annotation. 
Fix to background classes bug relating to [this bug report](https://github.com/v7labs/darwin-py/issues/526) and leading to an issue losing the first class annotation when using the SemanticSegmentationDataset object
> [IO-727] Changes to background class for SemanticSegmentationDataset

- darwin/importer/importer.py
- tests/darwin/importer/importer_test.py
**Summary**
@tomvars found a bug in the flow of the importer, by which logic for normal annotations, and logic for video annotations was being applied to both types in errata.  This has been corrected, along with unit test fixes and augmentations.
NB: A ticket is raised for refactoring the importer unit tests which have become untidy as a result of merging and refactoring in several areas: IO-841
* Refactored the importer to correctly separate flow of logic
* Refactored the tests to cover this.
> [IO-835][external] Fix for a logic flow bug in importer

- darwin/importer/importer.py
- tests/darwin/importer/importer_test.py
Removing the fourth input to _get_annotation_data as it's unnecessary and causes an issue with videoAnnotations.
fixed bug with video annotations import
> [IO-874] removing annotation data as input to _get_annotation_data

- darwin/utils/utils.py
d-py loops over known supported file extensions when "finding" images.
....JPG was not being found
Also look for files ending in .JPG
> [IO-914][Internal] Also look for files ending in .JPG

- darwin/importer/importer.py
Ticket for CS points out that some customers experience issues with multiprocessing, as although disabled by default in CLI, it isn't in SDK.
Have changed to be automatically not used unless user specifies the `use_multi_cpu` setting when invoking `import_annotations` and sets to `True`.  This means some imports may run slower, but the issues CS have seen will not happen.
> [V7-4587] [internal] Temporarily disabled multiprocessing in SDK unless explicitly set on

- darwin/torch/dataset.py
The torch classification dataset now throws an error if an image/video frame without tags is being loaded.
`assert len(tags) >= 1, f"No tags were found for index={index}`
We have now enabled training on such images as long as the dataset is multilabel. Binary or multiclass will still not work.
> Enabled multilabel training on images/video frames without tags

- darwin/future/core/client.py
- darwin/future/core/types/client.py
- darwin/future/data_objects/typing.py
- darwin/future/exceptions/__init__.py
- darwin/future/exceptions/base.py
- darwin/future/tests/core/test_client.py
- pyproject.toml
- test.py
Adding in the core api client functionality that can make generic http requets. Will be built on for the meta apiclient that is presented to the user and acts as a core base. 
- Generic call method that is invoked by oither calls, get/put/post etc
- Checks for known exceptions
Continuing work on darwin py v2 functionality. Added Core Client
> [IO-751] api client v2

- darwin/datatypes.py
- darwin/exporter/formats/mask.py
- tests/darwin/exporter/formats/export_mask_test.py
Small fix that unblocks databricks envs using darwin py.
> Made numpy typing optional to support old versions of numpy

- .github/workflows/document.yml
Update GitHub Action to use AWS OIDC role instead of AWS credentials.
Internal improvements around how AWS credentials are being used. At the same, this PR also upgrades `aws-actions/configure-aws-credentials` action to `v2` which unfortunately will present a warning about upgrading to JavaScript v3 (see [this issue](https://github.com/aws-actions/configure-aws-credentials/issues/680) for more details).
> [PLA-150][internal] Switch Github Action to use AWS role

- darwin/cli_functions.py
Handle 422 API response for dataset exports. When there is nothing to export we present:
```python
Error: Nothing to export
```
> [IO-1062][External] Handle 422 API response for dataset exports

- darwin/cli.py
- darwin/cli_functions.py
- darwin/dataset/download_manager.py
- darwin/dataset/remote_dataset.py
- darwin/options.py
- test.py
Adding in the option to forcibly ignore slots even if dataset includes slots. Defaults to taking the first slot item and building the regular flat structure
--ignore-slots option added to `dataset pull` command
> [Io-1103][Internal] --ignore-slots option added to dataset pull

- darwin/importer/importer.py
- darwin/utils/utils.py
This fixes an issue where `source_info` is required if any slots are provided. This doesn't need to be the case.
> [IO-1154][V7-5112][internal] Fix annotation import with no source_info

- darwin/backend_v2.py
- darwin/dataset/remote_dataset_v2.py
Filtering on dataset export currently uses the wrong filter REST payload and instead uses a filtering system intended for UI only use. 
Filters changed to use the same system as UI 'current filters' option rather than 'optionally filter by class'
> [IO-1067] Filtering by class ids

- darwin/exporter/formats/mask.py
- tests/darwin/exporter/formats/export_mask_test.py
Fix to the mapping of class colour mapping with semantic mask exports. Existing behaviour creates a new colour map for each file, leading to an issue where multiple file exports that have a mixture of classes between files get the wrong colour assigned to them. New logic pulls the colour from the category dictionary which is populated with the entire exports list of classes
Fix for class colour mapping in csv for semantic masks
> [IO-1138] Semantic Mask colour map fix

- darwin/exporter/formats/mask.py
- test/class_mapping.csv
- tests/darwin/exporter/formats/export_mask_test.py
Polygons that extend beyond the frame of reference (image height and width) get points truncated and this causes issues with the exported mask
Checks if any annotation exceeds the window frame, if so it creates a larger mask defined by the full extent of all polygons in the annotations, creating and then offsetting the polygons to capture the entire space, before subsampling the full mask with the image dimensions in the correct location
Resolved an issue where out of bounds polygons caused semantic mask exports to truncate points and generate a wrong mask
> [IO-1205] Semantic Mask annotations outside of frame

- darwin/dataset/download_manager.py
dots/periods in filenames cause the last 'segment' between the periods to be lost, and thus causing issues with filenames being downloaded/named incorrectly. This stems from issues with the .with_suffix() function. Replaced with stem + suffix solution that generates the correct filename
filenames with multiple dots now saving filenames correctly
> [IO-1081 ]fix for dot/period/. in filename

- darwin/importer/importer.py
- darwin/utils/utils.py
- tests/darwin/utils_test.py
This PR fixes few issues with Darwin rasters import:
* Raster specific annotation types are no "visible" on target datasets
* Raster specific annotation data now has proper depth to it
* Annotation ID is sent to import APIs if it's loaded for given annotation
> [IO-1189] Fix raster import

- darwin/exporter/formats/mask.py
- tests/darwin/exporter/formats/export_mask_test.py
Latest fix for semantic mask didn't account for the problem of having complex polygons vs simple polygons
Polygon offsets now account for complex polygons and deal with simple/complex accordingly
Fixed a problem with new semantic mask export logic not accounting for complex polygon datasets with out of bounds polygons. It should now handle complex polygons.
> [IO-1203] Fix and test for complex polygons

- darwin/future/meta/objects/dataset.py
- darwin/future/tests/meta/objects/test_datasetmeta.py
Meta objects had no way of creating datasets, which blocks workflows.
Added a simple create dataset function to the `DatasetMeta` object, with tests.
Implemented previously `NotRaisedException` raising function `create_dataset` on `DatasetMeta`
Added unit tests for creation of datasets.
> [IO-1018][internal] Create Dataset meta method

- darwin/dataset/remote_dataset_v2.py
- darwin/item.py
- tests/darwin/dataset/item_test.py
Dataset items created via parse method lack the workflow status, id and dataset slug fields
add parsing these into the object, dataset_slug is not a a part of the json response and has to be passed into the parse function manually, added in as an optional field with default of "n/a" to preserve any existing functionality
Items created via underlying parse method should correctly identify workflows they are attached to and the dataset they are a part of.
> [IO-1203] Missing dataset fields

- darwin/exporter/formats/yolo.py
File overwriting bug in YOLO conversions.
In a scenario where two files are in a directory structure with the same name:
```
|-image.json
|-image_2.json
|
|--folder_1
|    |-image.png
|--folder_2
|    |-image.png
```
The use of the `AnnotationFile` attribute `filename` is used to define the output filenames (`image.txt` and `image.txt`), and this causes a clash, in which one file output _overwrites_ the other.
Instead of using `AnnotationFile.filename`, it's better to use the `.stem` attribute of the path to the json file, as these are in the same directory, and can't share a name.
Changed file to use `Path.stem` instead of `AnnotationFile.filename`
> [IO-1341] YoloV2 file overwriting bug.

- e2e_tests/e2e_test.md
No provision for E2E tests in darwin-py
Added configured pytest module.
Added pytest module
Added pytest.ini fule
Added minor docs.
> [IO-1331][internal] Introduce E2E tests module

- e2e_tests/.env.sample
- e2e_tests/conftest.py
- e2e_tests/exceptions.py
- e2e_tests/pytest.ini
- e2e_tests/test_example.py
E2E Tests had no config solution
Added a `conftest.py` file that incoporated environment variables, with optional `dotenv` for use on local machines.  Also added a fixture that is global, and session bound (runs once per test session, not once per test) that allows for these values to be included in tests easily.  Have also added custom E2E exceptions that the config code can raise so that if our system raises an error we foresee in config, we can easily spot these in CI.
*NB: Have deliberately not included the staging URL in the defaults, as it would go into our public code if I did, and possibly shouldn't*.
e2e_tests/conftest.py
e2e_tests/exceptions.py
e2e_tests/pytest.ini
e2e_tests/test_example.py
* Added test configuration file with hook to accept and parse config, and fixture to …
> [IO-1334][internal] E2E Testing config

- darwin/future/core/datasets/remove_dataset.py
- darwin/future/core/types/query.py
- darwin/future/meta/client.py
- darwin/future/meta/queries/dataset.py
- darwin/future/meta/queries/stage.py
- darwin/future/meta/queries/team_member.py
- darwin/future/meta/queries/workflow.py
- darwin/future/tests/core/test_client.py
- darwin/future/tests/core/test_query.py
QueryFilter objects are a bit unweildy atm, having to call them with a quite verbose dictionary like syntax
Added in ability to create filter objects from kwargs while keeping existing functionality, also supports modifier instantiation using 'modifier:value' syntax
```python
QueryFilter._from_args(test='test1') # QueryFilter(name='test', param='test1')
QueryFilter._from_args(test='>=:6') # QueryFilter(name='test', param='6', modifier='>=')
```
Also cleaned up Query code further to handle generalized and inherited `where(*args, **kwargs)` that creates these filter objects and doesn't require overwriting in meta query code.
Streamlined creation and usage of QueryFilters
> QF refactor and mypy cleanup

- darwin/future/core/client.py
- darwin/future/core/items/get.py
- darwin/future/core/items/move_items.py
- darwin/future/core/items/move_items_to_stage.py
- darwin/future/core/types/query.py
- darwin/future/data_objects/team.py
- darwin/future/data_objects/workflow.py
- darwin/future/meta/client.py
- darwin/future/meta/objects/base.py
- darwin/future/meta/objects/dataset.py
- darwin/future/meta/objects/stage.py
- darwin/future/meta/objects/team.py
- darwin/future/meta/objects/workflow.py
- darwin/future/meta/queries/dataset.py
- darwin/future/meta/queries/stage.py
- darwin/future/meta/queries/workflow.py
- darwin/future/tests/core/fixtures.py
- darwin/future/tests/core/items/fixtures.py
- darwin/future/tests/core/items/test_get_items.py
- darwin/future/tests/core/items/test_move_items.py
- darwin/future/tests/core/test_client.py
- darwin/future/tests/core/test_query.py
- darwin/future/tests/data_objects/fixtures.py
- darwin/future/tests/meta/objects/test_stagemeta.py
Don't have any way to move items around workflows in darwin-py at the moment
Add in functions to stage items as well as backend core functions to move items
Can move items in workflows, see item's attached to a stage and manage workflows better
> [IO-1279] Functions to move items around stages

- darwin/exporter/formats/__init__.py
- darwin/exporter/formats/helpers/yolo_class_builder.py
- darwin/exporter/formats/yolo.py
- darwin/exporter/formats/yolo_segmented.py
- tests/darwin/exporter/formats/export_yolo_segmented_test.py
We don't support YoloV8 Segmentation
Have implemented YoloV8 Segmentation datasets.
Added new Yolo segementation exporter
Added Yolo shared helpers
Added social test for the exporter
> [IO-1405][external] YoloV8 Segementation dataset support

- README.md
- darwin/cli_functions.py
- darwin/dataset/remote_dataset.py
Right now, after you download the dataset via `dataset pull` one of the messages is `Going to download ... files to /Users/..../images.`. 
As is, when you copy this path you also copy the dot in the end, which leads to `/Users/...../images. does not exist.`. This is inconvenient.
Separate the path and the dot in the message formatting. 
Improve dataset download message.
> Update CLI dataset pull success message

- darwin/dataset/download_manager.py
- darwin/dataset/remote_dataset.py
```
> $ darwin dataset pull longvideosnoframes/videos-no-frames-extraction:2 --video-frames                                 
Error: Missing Dependency: OpenCV required for Video Extraction. Install with `pip install darwin[ocv]`
> $ pip install darwin\[ocv\]                                                                                           
ERROR: Could not find a version that satisfies the requirement darwin[ocv] (from versions: none)
ERROR: No matching distribution found for darwin[ocv]
```
Rename `darwin[ocv]` -> `darwin-py[ocv]`
> Fix name of ocv package

- darwin/exporter/formats/yolo_segmented.py
- tests/darwin/exporter/formats/export_yolo_segmented_test.py
YoloV8 was misidentifying items as complex polygons and refusing to export them.
Improved identification logic, and added test case and tolerated old scenario in case it's needed for anything.
Refactor to YoloV8 exporter
Test added
> [IO-1607][internal] Hotfix for Yolov8

- darwin/exporter/formats/yolo_segmented.py
- tests/darwin/exporter/formats/export_yolo_segmented_test.py
Further fix for Yolo as the geometry was backwards for bounding box corners.
Reversed appropriate corners.
Changed bb code
Changed tests
> Hotfix IO-1607

- darwin/client.py
- tests/darwin/client_test.py
On occasion, the API returns a nullish response instead of 0 for a zero count item, image or video count, which causes a crash
Have written a single function that calculates the item count for each dataset, based on appropriate elimination logic
New function to calculate item counts, applied to all creations of `RemoteDatasetV1` and `RemoteDatasetV2` items.
Tests for new function
Tests to ensure that client and new function behave correctly _together_
Some cleanup of old typing and linting
> [IO-1626][external] Client fails when data structure is unexpected

- darwin/dataset/split_manager.py
When using the split_dataset method with small datasets, such as 7 images and a low validation or test split %, we can end up in a situation where we get zero images in the test or val set since we do the rounding by converting to an int. This will cause unnecessary crashing of the code.
```
test_percentage = 0.1
dataset_size = 7
int(dataset_size * test_percentage)
> 0
```
By changing the rounding to math.ceil we would not end up in a case where val or test is 0 if not specifically the percentage is set to 0. Making the code more robust.
- split_dataset Method:
Problem: Small datasets with low split percentages resulted in zero images for test or validation due to integer rounding.
Solution: Changed rounding to math.ceil to ensure non-zero splits unless explicitly set to 0%.
> changed rounding of val and test from int convertion to math.ceil

- darwin/future/data_objects/workflow.py
- darwin/future/tests/meta/queries/test_stage.py
WFType enum doesn't accept unknown values and this breaks certain testing with older/experimental Workflow types
Introduce default parsing that accepts unknown values and casting them to an UNKNOWN enum type
Workflow stage enum no longer breaks on experimental and testing types
> [IO-1464] add in unknown parsing for WFTypes

- darwin/utils/utils.py
We made sparse_rle field non required and don't save it in the db anymore. Validation in darwin-py must reflect it.
Adjust import validation
Make `sparse_rle` field of mask annotations optional during import
> [ANN-2419][internal] Make mask annotation's sparse_rle field optional

- darwin/dataset/local_dataset.py
- darwin/dataset/utils.py
- darwin/utils/utils.py
`LocalDataset` and other functions that read and parse local files (generally used to train models) do not support Darwin 2.0 format datasets. As it is implemented now, these functions assume datasets are 1.0 so they'll crash when loading a 2.0 dataset due to the mismatch of fields.
Standardize the use of the util function `parse_darwin_json` across all these functions, which already abstracts dataset formats and supports both 1.0 and 2.0.
- Support for Darwin 2.0 datasets in `LocalDataset`
- Support for Darwin 2.0 datasets in `get_coco_format_record`
> Update local datasets to darwin 2.0

- darwin/dataset/download_manager.py
- darwin/dataset/remote_dataset.py
CV2 can fail to import videocapture function and fail elsewhere that isn't captured
Make sure cv2 and videocapture function are imported
cv2 failed import should now print the right error message if VideoCapture function isn't found
> [IO-1565] video capture check

- darwin/utils/utils.py
- tests/darwin/utils_test.py
Slot name is a required field, contrary to other annotation types 
Remove the requirement checks that fail
Rasters and Masks now no longer require slot names, in line with schema
> [IO-1739] Slot names mistakenly required for mask/rasters

- darwin/datatypes.py
- darwin/utils/utils.py
When importing mask annotations for a video item, darwin-py skips them with next warning:
`[WARNING] Unsupported annotation type: 'dict_keys(['keyframe', 'mask', 'name', 'id'])'`
Add logic for reorganizing such annotations as valid once. 
Fixed bug when it is not possible to import mask annotations for a video
> [ANN-2555][External] Fixed bug when it is not possible to import mask annotations for a video

- darwin/torch/dataset.py
- darwin/torch/transforms.py
- darwin/torch/utils.py
- darwin/utils/utils.py
- pyproject.toml
- tests/darwin/torch/dataset_test.py
- tests/darwin/torch/utils_test.py
We want to introduce the possibility to use Albumentation transforms with darwin-py torch datasets. 
Introducing an `AlbumentationsTransform` class in torch.transforms that can be be used in the following manner:
```
from darwin.torch.dataset import (
ClassificationDataset,
InstanceSegmentationDataset,
ObjectDetectionDataset,
SemanticSegmentationDataset,
)
from darwin.torch.transforms import AlbumentationsTransform
dataset_path = Path(r"/path/to/local/darwin/dataset")
transform = AlbumentationsTransform.from_path('/tmp/transform.json')
inst_dataset = InstanceSegmentationDataset(dataset_path=dataset_path, transform=transform)
```
One can initilize the `AlbumentationsTransform` in three ways:
- AlbumentationsTransform(albumentation_transform) <- needs an albumentations transformation
- …
> [AI-1190] Implement and test augmentations

- .github/workflows/document.yml
- .gitignore
- README.md
Documentation will currently not build because of benign Sphinx errors
Remove `-W` flag from Sphinx build, and ticket the fix properly
Changed `document.yml` to tolerate warnings from Sphinx
> [IO-1824][internal] Documentation fix

- e2e_tests/helpers.py
- e2e_tests/test_darwin.py
- tests/e2e_test_internals/test_run_cli_command.py
Timing on e2e tests can cause failures based on whether the server has fully executed the commands before running new code that interacts with those datasets/items
- Change the timing between tests
- Add unified approach to delay
- Add unified approach to testing cli results
e2e tests should be less timing based
> [IO-1829] Tests refactor and timing changes

- darwin/importer/formats/coco.py
COCO `iscrowd` error messages were not clear to customers.
Have changed the messages to explain more verbosely what the issue is with a crowd import.
`coco.py` now uses `logger`, and the message is more verbose
> [IO-1661][external] Error messages were not clear to customers

- darwin/dataset/download_manager.py
- darwin/dataset/remote_dataset.py
As described in [this](https://github.com/v7labs/darwin-py/issues/603) GitHub issue, pulling two different releases using `RemoteDataset.pull()` passing `with_folders=True` **can** result in missing files from the second release unless `force_replace=True` is passed as well. This is because `pull()` does not download files if the stem of the filename is 
already present anywhere in the `~/.darwin/datasets/{team_slug}/{dataset_slug}/images` folder.
A further breakdown of the cause is available in the Linear ticket [IO-1586
](https://linear.app/v7labs/issue/IO-1586/bug-external-issue-with-sequential-dataset-pull-operations)
Instead of checking the stem of existing filenames in the images folder, check the full local filepath of each file against the "planned" local path for each file in the …
> [IO-1586][external] Changes to RemoteDataset.pull() to account for identically named files in different export releases

- darwin/future/core/items/get.py
- darwin/future/core/team/__init__.py
- darwin/future/core/types/common.py
- darwin/future/core/types/query.py
- darwin/future/core/utils/pathutils.py
- darwin/future/core/workflows/list_workflows.py
- darwin/future/data_objects/item.py
- darwin/future/data_objects/release.py
- darwin/future/data_objects/team.py
- darwin/future/exceptions.py
- darwin/future/meta/objects/dataset.py
- darwin/future/meta/objects/stage.py
- darwin/future/meta/objects/team.py
- darwin/future/meta/objects/workflow.py
- darwin/future/meta/queries/dataset.py
- darwin/future/meta/queries/team_member.py
- darwin/future/tests/core/datasets/test_list_datasets.py
- darwin/future/tests/core/items/fixtures.py
- darwin/future/tests/core/items/test_get_items.py
- darwin/future/tests/core/test_query.py
- darwin/future/tests/core/types/test_querystring.py
- darwin/future/tests/data_objects/fixtures.py
- darwin/future/tests/data_objects/workflow/test_wfedge.py
- darwin/future/tests/data_objects/workflow/test_wfstage_config.py
- darwin/future/tests/data_objects/workflow/test_wfuser.py
- darwin/future/tests/meta/objects/test_stagemeta.py
- darwin/future/tests/meta/queries/test_workflow.py
- pyproject.toml
No ability to retrieve or manage items and folders
- Introduce basic item object
- backend calls for item and folders endpoints
Beggining of support for items object, including apis
> [IO-1278][IO-1277] Core Items/Folders apis

- darwin/future/core/items/set_priority.py
- darwin/future/tests/core/items/test_set_priority.py
No current access to setting priority of items
Implemented priority setter.
Priority setting method in core
Tests
> [IO-1800] Set priority

- .hooks/typechecking_installer.sh
- darwin/future/core/items/move_items.py
- darwin/future/meta/objects/base.py
- darwin/importer/formats/coco.py
We now have linting and typechecking on the darwin-py future code but no non-manual way to ensure this code is up to scratch before creating a PR
Add in a typechecking optional pre/post commit hook script
install via `./.hooks/typechecking_installer.sh -o/-p` -o default for post-commit (non-blocking warning) vs -p pre-commit (strictly enforced), 
Optional developer installable git hooks
> Intro git hooks for typechecking

- docs/DEV.md
- poetry.toml
Setting up poetry config is a manual process - Instructions here: https://github.com/v7labs/darwin-py/blob/master/docs/DEV.md#poetry
Adding poetry configurations in a [Local configuration](https://python-poetry.org/docs/configuration/#local-configuration) file poetry.toml to make our life easier :)
Configuration Docs:
- [virtualenvs.in-project](https://python-poetry.org/docs/configuration/#virtualenvsin-project)
- [virtualenvs.prefer-active-python](https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental)
[dev] Move Poetry Configuration to `poetry.toml`
> add poetry config file `poetry.toml`

- darwin/future/core/datasets/list_datasets.py
- darwin/future/core/datasets/remove_dataset.py
- darwin/future/core/items/get.py
- darwin/future/core/team/get_raw.py
- darwin/future/core/team/get_team.py
- darwin/future/core/types/common.py
- darwin/future/core/types/query.py
- darwin/future/core/workflows/get_workflow.py
- darwin/future/data_objects/pydantic_base.py
- darwin/future/exceptions.py
- darwin/future/meta/client.py
- darwin/future/meta/objects/base.py
- darwin/future/meta/objects/dataset.py
- darwin/future/meta/objects/stage.py
- darwin/future/meta/objects/team.py
- darwin/future/meta/objects/team_member.py
- darwin/future/meta/objects/workflow.py
- darwin/future/meta/queries/stage.py
- darwin/future/tests/core/datasets/test_list_datasets.py
- darwin/future/tests/core/items/test_get_items.py
- darwin/future/tests/core/workflows/test_get_workflow.py
- darwin/future/tests/meta/objects/test_datasetmeta.py
- darwin/future/tests/meta/objects/test_stagemeta.py
- darwin/future/tests/meta/objects/test_teammeta.py
- pyproject.toml
Some undocumented code and dogfooding issues have accrued
fix the following:
- added documentation as well as examples
- refactored and unified approach to exception handling
- swapped str/repr locations to conform with mypy typechecking
The List[Exception] Paradigm now only exists for things that parse multiple objects. It should raise on other issues like exceptions from underlying http request, but will attempt to parse all objects before failing. 
Added documentation and dogfooding refactors to futures code
> [IO-1461][IO-1820] Code Documentation + exception refactoring + mypy checking

- darwin/future/core/client.py
- darwin/future/core/items/archive_items.py
- darwin/future/exceptions.py
- darwin/future/tests/core/items/test_archive_items.py
Currently no way to archive items in `darwin.future`
Define the core method to archive a list of items by their UUIDs by using the archive endpoint
Added core item archive method & tests
> [IO-1801][external] Core item archive method & tests

- darwin/future/core/items/set_item_priority.py
- darwin/future/core/items/set_priority.py
- darwin/future/tests/core/items/test_set_priority.py
The initial set priority had opportunity for some improvements
Made the improvements
> [IO-1800][internal] Set Priority of items

- darwin/future/core/client.py
- darwin/future/core/items/delete_items.py
- darwin/future/tests/core/items/test_delete_items.py
Currently no way to delete items in `darwin.future`
Define the core method to delete a list of items by their UUIDs by using the delete endpoint
Added core item delete methods & tests
> [IO-1805][external] Core delete item method & tests

- darwin/exporter/formats/darwin.py
- darwin/exporter/formats/nifti.py
As described in [IO-2040](https://linear.app/v7labs/issue/IO-2040/bug-there-is-an-issue-exporting-nifti-that-is-not-an-issue-for-darwin), NifTI exports of files with filenames containing dots would fail due to there being too many suffixes
Add logic to extract the last 2 suffixes of each filename while preserving the existing error checking logic
Fixed a bug preventing NifTI exports that include filenames with dots
> [IO-2040][external] Fix for NifTI exports that include filenames with dots

- darwin/future/core/items/restore_items.py
- darwin/future/tests/core/items/test_restore_items.py
Currently no way to restore items in `darwin.future`
Define the core method to restore a list of items by their UUIDs by using the restore endpoint
Added core item restore method & tests
> [IO-1802][external] Added core item method to restore items + tests

- darwin/future/core/client.py
- darwin/future/core/items/move_items_to_folder.py
- darwin/future/exceptions.py
- darwin/future/tests/core/datasets/test_create_dataset.py
- darwin/future/tests/core/datasets/test_delete_dataset.py
- darwin/future/tests/core/datasets/test_get_dataset.py
- darwin/future/tests/core/datasets/test_list_datasets.py
- darwin/future/tests/core/items/test_move_items_to_folder
- darwin/future/tests/core/items/test_move_items_to_folder.py
- darwin/future/tests/core/workflows/test_get_workflow.py
- darwin/future/tests/core/workflows/test_get_workflows.py
- darwin/future/tests/core/workflows/test_list_workflows.py
Currently no way to move items between folders in `darwin.future`
Define the core method to move a list of items by their UUIDs by using the path endpoint
Added core method to move items between folders
> [PY-386][external] Core method to move items between folders & tests

- darwin/backend_v2.py
- darwin/cli.py
- darwin/cli_functions.py
- darwin/dataset/download_manager.py
- darwin/dataset/remote_dataset.py
- darwin/dataset/remote_dataset_v1.py
- darwin/dataset/remote_dataset_v2.py
- darwin/dataset/upload_manager.py
- darwin/datatypes.py
- darwin/exceptions.py
- darwin/exporter/exporter.py
- darwin/exporter/formats/coco.py
- darwin/exporter/formats/dataloop.py
- darwin/exporter/formats/mask.py
- darwin/exporter/formats/nifti.py
- darwin/exporter/formats/pascalvoc.py
- darwin/exporter/formats/yolo_segmented.py
- darwin/importer/formats/coco.py
- darwin/importer/formats/csv_tags.py
- darwin/importer/formats/csv_tags_video.py
- darwin/importer/formats/dataloop.py
- darwin/importer/formats/labelbox.py
- darwin/importer/formats/nifti.py
- darwin/importer/formats/pascal_voc.py
- darwin/importer/importer.py
- darwin/torch/__init__.py
- darwin/torch/dataset.py
- darwin/torch/utils.py
- darwin/utils/utils.py
- tests/darwin/importer/formats/import_dataloop_test.py
Existing issues in older code can be automatically applied via ruff tool
run `ruff --fix` on existing code, applying changes
ruff based automatic changes applied to existing code
> automatic ruff --fix changes

- darwin/datatypes.py
- darwin/utils/utils.py
Long videos currently does not get split correctly for formats like coco that require treating each image seperately. 
Added in logic for generation of split video annotations if frame_urls is not present, relying instead on frame_count, which is a field to be added in conjunction with changes to slots
split video annotations should now work correctly with long video files
> [PY-627] Long Video support for split video annotations

- darwin/future/meta/objects/base.py
- darwin/future/meta/objects/item.py
Printing the `Item` class raises RecursionError
```python
from darwin.future.meta.client import Client
dataset = client.team.datasets.collect()[-1]
print(dataset.items.where().collect())
```
```console
Traceback (most recent call last):
File "t4.py", line 15, in <module>
raise SystemExit(main())
File "t4.py", line 8, in main
print(dataset.items.where().collect())
File "/Users/saurabhchopra/github/v7labs/darwin-py/darwin/future/meta/objects/base.py", line 50, in __repr__
return str(self)
File "/Users/saurabhchopra/github/v7labs/darwin-py/darwin/future/meta/objects/base.py", line 50, in __repr__
return str(self)
File "/Users/saurabhchopra/github/v7labs/darwin-py/darwin/future/meta/objects/base.py", line 50, in __repr__
return str(self)
[Previous line repeated 329 more times]
RecursionError: …
```
> Fix `RecursionError` in `Item` class

- darwin/exporter/formats/nifti.py
Unable to export Nifti files without file extension.
This is a bug, which should be performing checks on slot's `file_name`. 
Updated the `filename` checks to work on slot level.
Fix Nifti file export without a file extension.
> [PY-613] BUG: Unable to export Nifti files without file extension.

- darwin/importer/formats/csv_tags_video.py
Currently, CSV video tag imports assume items are in a flat folder structure, meaning the importer ignores files in folder structures.
Added logic to pull out and consider the remote path when importing
Added support for folder structures when importing CSV video tags
> [PY-605][external]Added support for folder structures when importing CSV video tags

- darwin/future/data_objects/advanced_filters.py
- darwin/future/tests/data_objects/test_advanced_filters.py
Darwin py has no support for upcoming advanced filters feature
Adding in the data objects mapped to our API pitch docs + object creation methods
[future] now has data objects for advanced filters
> [PY-599] Advanced Filter objects

- darwin/client.py
`stage_id` was mistakenly typed as `int` in `darwin/client.py`
Type as `str`
Small typing fix for `stage_id`
> [PY-641][external] Small typing change to stage_id

- darwin/future/core/items/set_stage_to_items.py
- darwin/future/meta/objects/dataset.py
- darwin/future/meta/objects/item.py
- darwin/future/meta/objects/workflow.py
- darwin/future/meta/queries/item.py
- darwin/future/tests/core/fixtures.py
- darwin/future/tests/core/items/test_set_stage_to_items.py
- darwin/future/tests/meta/objects/fixtures.py
- darwin/future/tests/meta/objects/test_itemmeta.py
- darwin/future/tests/meta/objects/test_workflowmeta.py
Feature Request to set a 'Workflow Stage' to an Item/ItemQuery object.
Implement `item.set_stage` on both Item and ItemQuery level.
1. there are 2 arguments to set_stage:
- `stage_or_stage_id` - you can pass either a Stage object OR stage_id str.
- `workflow_id` is optional. If this is called via workflow object then set_stage will infer workflow_id from workflow meta_params. Otherwise, then workflow_id is required.
2. Updated workflow meta object attribute `items`. It was calling the list_items API with workflow_id as QueryParam, removed it, and added `workflow_id` with value of self.id,`dataset_ids` in meta_params with value as the 1st dataset stage id (assuming a workflow only has 1 dataset stage).
- Updating stage for Item(s) via workflow object 
```python
workflow = …
```
> [PY-542] Set stage

- darwin/dataset/local_dataset.py
- darwin/exporter/formats/darwin_1_0.py
- darwin/importer/formats/csv_tags_video.py
- darwin/importer/importer.py
- darwin/torch/dataset.py
- darwin/utils/utils.py
As described in PY-646, sufficiently small polygons can result in an assertion error due to rounding 4 decimal place floats to integers. This can cause the minimum & maximum x or y coordinates of the enclosing bounding box to be equal, resulting in a "flat" bbox with no area that is therefore invalid
Pass the `rounding` arg as `False` to prevent this
Resolved rounding error for very small polygons in Pytorch dataloaders
> [PY-646][external]Resolved precision bug & some linting

- darwin/dataset/local_dataset.py
- darwin/exporter/formats/darwin_1_0.py
- darwin/importer/formats/csv_tags_video.py
- darwin/importer/importer.py
- darwin/torch/dataset.py
- darwin/utils/utils.py
This reverts commit 254d05adeb417596c2cd4bc1cc06a8d227dbf6d1.
Merged accidentally without QA
Revert
Revert so change can be QA'd first
> Revert "Resolved precision bug & some linting (#751)"

- darwin/importer/importer.py
Silently ignore "empty" masks (i.e. masks that do not have a corresponding raster layer) during import
During import, checking if the mask annotation is present in `raster_layer` - then further checking the same in the whole `dense_rle` flat array, if not present, don't import the mask (i.e., remove the mask annotation from import request data and also remove it from raster_layer mask-mapping)
Silently ignore "empty" masks (i.e. masks that do not have a corresponding raster layer) during import
> [PY-611] Silently ignore "empty" masks during import

- darwin/client.py
- darwin/torch/dataset.py
- darwin/utils/utils.py
As described in PY-646, sufficiently small polygons can result in an assertion error due to rounding 4 decimal place floats to integers. This can cause the minimum & maximum x or y coordinates of the enclosing bounding box to be equal, resulting in a "flat" bbox with no area that is therefore invalid
Pass the `rounding` arg as `False` to prevent this
Resolved rounding error for very small polygons in Pytorch dataloaders
> [PY-646][external] Resolved precision bug

- darwin/future/core/client.py
- darwin/future/core/datasets/create_dataset.py
- darwin/future/pydantic_base.py
Some latent issues exists regarding recent pydantic 1.x -> 2.x changes
Change the root validator for config, and protected namespaces of default darwin object
Fixed a bug stopping client from instantiating with recent pydantic changes
> Config changes required for pydantic model updates

- darwin/importer/importer.py
- tests/darwin/importer/importer_test.py
No support for handling properties data in import_annotation endpoint
add another function `_handle_properties` which adds `properties` as list of property data (as required by backend)
TODO:
Updates to import endpoint - Handle Properties data
> [PY-626] Updates to import endpoint - `annotation_properties`

- .github/CODEOWNERS
We don't need the CODEOWNERS logic any more.
Remove CODEOWNERS file.
> [DAR-5][internal] Remove CODEOWNERS from darwin-py

- darwin/datatypes.py
- darwin/future/data_objects/properties.py
- darwin/importer/importer.py
- darwin/utils/utils.py
- tests/darwin/data/metadata.json
- tests/darwin/data/metadata_nested_properties.json
- tests/darwin/datatypes_test.py
Import breaks with properties, when parsing 'options' from Property in .v7/metadata.json
- `options` is moved to `property_values`
- `type` field is Optional[str] now.
Additional Changes:
- `frame_index` for Video Annotation is fixed (per-annotation)
- fix the annotation-import payload in case of null property-values
[Bug] Property import fixed, `options` -> `property_values`, `frame_index` fixes
> [Bug] Property import fixed, `options` -> `property_values`

- darwin/exporter/formats/darwin_1_0.py
- darwin/importer/importer.py
- tests/darwin/exporter/formats/export_darwin_1_0_test.py
A previous PR introduced in 0.8.45 broke the following annotation types when converting from 2.0 to 1.0 JSON:
- Cuboid
- Ellipse
- Keypoint
- Skeleton
- Introduced logic to handle these types during conversion
- Added a test for this logic
Fixed a bug that prevented certain annotation types from being converted from 2.0 to 1.0 JSON
> [DAR-214][external Fixed unhandled annotation types in 1.0 conversion

- darwin/dataset/local_dataset.py
- darwin/dataset/remote_dataset.py
- darwin/dataset/utils.py
- darwin/importer/importer.py
darwin-py uses multi-threading and multi-processing, but currently everything is labelled as multi-threading
Identified and re-named multi-processing functions from `multi_threaded` to `multi_processed`
- Correctly labelled multi-processed functions as multi-processed instead of multi-threaded
> [PY-658][external] Identified and correctly named all multi-processed functions

- darwin/dataset/remote_dataset_v2.py
The `fetch_remote_files()` method does not accept `item_paths` as a filter
This led to some confusion as this was shown as being possible as per the following recipe: https://docs.v7labs.com/recipes/list-datasetitems-from-remotedataset-sdk
Allow `item_paths` to be passed as a filter to `fetch_remote_files()`
Fixed bug preventing filtering by item path for an SDK function
> [PLA-548][external] Resolved issue with item path filtering

- darwin/exporter/formats/nifti.py
Users of Darwin can currently annotate as masks but not export these results to NifTI
We create a new code path within the same NifTI export logic. This means that for darwin JSON that contains polygons we will still parse these as before and output a NifTI volume. If the user has K mask classes they will receive K output files called `SeriesInstanceUID_classname_m.nii.gz` (NOTE: for nifti uploads SeriesInstanceUID is the filename)
Introduced initial support for NifTI export from Masks
> [MED-23][external] Support for export from Raster Layer to NifTI

- darwin/importer/importer.py
- e2e_tests/cli/convert/test_convert.py
- tests/darwin/importer/importer_test.py
- tests/darwin/path_utils_test.py
As of now, when importing annotations, we automatically make every keyframe a "sub-annotation keyframe" by marking that the sub-annotation has changed.
> during import, between D-Py and backend we still use this format which include both annotation and sub-annotation data at the same time, for each "keyframe". It would be kinda-possible to drop sub-annotation data from the request whenever we know it didn't change since last one, which likely wouldn't create on backend side sub-annotation keyframe.
Don't create sub-annotation keyframe for every keyframe when importing annotations
> [PLA-595] Don't create sub-annotation keyframe for every keyframe when importing annotations

- darwin/importer/importer.py
While importing annotations with properties, property-values which are not in annotation file but present in metadata.json are not created/updated in annotation-property.
Adding additional logic after annotation-properties are created/updated on the server. Logic is:
1. get the latest team-properties
2. only go ahead in the case when annotation-properties are present in team-properties
3. _build metadata-property-values set_
4. _build team-property-values set_
5. extra values: _diff b/w metadata & team property-values set_
6. update property with extra-property-values!
Updating additional metadata property values while importing annotations
> [PLA-640] Updating metadata property values while importing annotations

- darwin/datatypes.py
- darwin/utils/utils.py
- tests/darwin/dataset/remote_dataset_test.py
- tests/darwin/utils_test.py
We added new field to the video annotation - `hidden_areas`.
Add logic which takes the field into account during import,
> [DAR-991][Internal] Add support of hidden_areas to darwin py importer

- darwin/datatypes.py
- darwin/importer/importer.py
- darwin/utils/utils.py
The optional `simple_table` annotation type can be exported, but not imported with darwin-py. This is because darwin-py doesn't have an annotation constructor for this type
Added a `make_simple_table()` function 
Added support to darwin-py for importing simple_table annotations
> [PLA-672][external] Support for importing simple_table annotations

- darwin/datatypes.py
- darwin/exporter/formats/mask.py
- tests/darwin/exporter/formats/export_mask_test.py
The same semantic mask could be represented by different colors in the files of the same export.
The root cause of the issue is an assumption that labels in the `raster_layer.data.mask_annotation_ids_mapping` are the same across different files which is not true. Because of that assumption labels were used as colors ids causing the mismatch.
I changed the logic to have static color ids for all files and convert labels into color ids for every file separately. 
Fix colours mismatch between files on semantic mask export
> [DAR-1104][External] Fix colours mismatch between files on semantic mask export

- darwin/exporter/formats/mask.py
- tests/darwin/exporter/formats/export_mask_test.py
Fix of the issue found in the accidentally merged PR - https://github.com/v7labs/darwin-py/pull/789
> [DAR-1104][Internal] Fix colours mismatch between files on semantic mask export

- .github/dependabot.yml
running tests for #786, I noticed out of date github-actions.
I've added a dependabot config(s) to make sure we stay relatively up to date.
- for github-actions to run weekly
- for pip to run weekly and ignore major version updates (as it could be breaking changes)
Add dependabot for pip and GitHub Actions
> [PLA-702] Add dependabot for pip and GitHub Actions

- darwin/datatypes.py
- darwin/exporter/formats/mask.py
- darwin/importer/importer.py
- tests/darwin/exporter/formats/export_mask_test.py
- tests/darwin/importer/importer_test.py
Currently, annotations with properties can only be imported if the annotation has an ID in the JSON file. Annotation IDs are not required for any other import functionality, so we should remove this requirement
When importing annotations, if an annotation does not have an ID, give it one with `uuid.uuid4()`. This works because we don't actually respect the ID that's assigned during import (to avoid clashes), it just needs to be a unique value per annotation
Removed the requirement for annotation IDs to be present in imported JSON to successfully import properties
> [PLA-639][External] Allow properties to be imported for annotations without IDs

- darwin/client.py
- darwin/future/core/client.py
- darwin/future/tests/core/test_client.py
- darwin/importer/importer.py
- tests/darwin/client_test.py
- tests/darwin/importer/importer_test.py
When importing annotations with properties to a non-default team, a codepath is invoked that creates a client object that is always for the default team as per the `config.yaml` file. This results in an authorization error for non-default teams
Create a client object that is for the team containing the target dataset
Fixed a bug when importing annotations to non-default teams
> Fixed bug when importing annotations with properties to non-default teams

- darwin/cli_functions.py
- darwin/dataset/remote_dataset_v2.py
- darwin/importer/importer.py
- tests/darwin/cli_functions_test.py
- Changes made to darwin-py in 0.8.58 to remove V1 code removed a V1 backwards compatibility "handler" for an older version of a filter parameter when retrieving a list of remote files in `fetch_remote_files()`
- Re-add this backward compatibility and update all invocations of `fetch_remote_files()` to use `item_names` instead of `filenames`
- Re-added backward compatibility for a V1 filter parameter when fetching remote files
> [PLA-801][external] fetch_remote_files() is called with an old, V1 argument

- darwin/client.py
- darwin/dataset/remote_dataset_v2.py
- darwin/dataset/utils.py
- darwin/importer/importer.py
- tests/darwin/dataset/remote_dataset_test.py
Instead of 2 client-facing registration functions, it's better UX to have a single function which takes an optional `multi_slotted` flag
Combine `register()` & `register_multi_slotted()` functions into a single `register()` function with an optional `multi_slotted` argument
Improved UX for external storage registration with darwin-py
> [PLA-753][External] Combine the register & register_multi_slotted functions

- .github/dependabot.yml
Dependabot was submitting dependency updates weekly in individual PRs, making it difficult to manage
Change frequency to monthly, and group PRs for ease of testing
Improved dependabot config to make it more manageable
> [DAR-1654][External] Updated dependabot config

- .github/workflows/JOB_generate_documentation.yml
- .github/workflows/JOB_tests.yml
From https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json, Python 3.8 and Python 3.9 is not available for Arm64 / MacOS.
Exclude Python 3.8 and 3.9 test for MacOS.
> [PY-668][Internal] Exclude macos from testing on 3.8 and 3.9

- darwin/exporter/formats/nifti.py
The polygons at Coronal and Sagittal are not exported.
Go through all the slots to ensure all the polygons are exported. 
Fixes DAR-1165
Fixes DAR-1734
- Polygon from Coronal and Sagittal plane are exported correctly.
> [DAR-1165][DAR-1734][External] Polygons from other plane export correctly

- darwin/backend_v2.py
- darwin/cli.py
- darwin/cli_functions.py
- darwin/importer/importer.py
- darwin/options.py
- tests/darwin/importer/importer_test.py
When importing annotations to a dataset item with existing annotations, unless `append` is set to `True`, the current annotations will be overwritten. Several users have been inconvenienced by the lack of warning when doing this
Introduce a by-passable warning that presents users with the potential impact of their import **if** any item targeted in the import has annotations. The warning is not displayed if:
- No item targeted by the import has annotations, or:
- The `--overwrite` option is set to `True` when executing the import
Introduced a by-passable warning when performing an annotation import that would overwrite existing annotations
> [DAR-1657][External] Introduce by-passable warning when an import will overwrite annotations

- darwin/importer/formats/csv_tags.py
- tests/darwin/importer/formats/import_csv_tags_test.py
- tests/darwin/importer/formats/import_csv_tags_video_test.py
When importing CSV tags, the importer currently sends one request per tag per item. If importing multiple tags to the same item, this can be sped up by bundling tags bound for the same item in the same request
This PR groups tags bound for the same item into the same request payload, and adds unit tests. I only had to implement this for `csv_tags`, since it turns out this was already implemented for `csv_tags_video`
I thought about splitting up annotation payloads if they grow beyond a certain size, but I tested up to 100000 tags in a single payload without issue
Improved speed of CSV tag importer when importing multiple tags to the same dataset item
> [DAR-2044][External] Bundle tags bound for the same item when using CSV importer

- darwin/dataset/local_dataset.py
- darwin/dataset/utils.py
- darwin/utils/utils.py
The call of this function is missing the `annotation_path` argument in `_map_annotations_to_images()`
Add this argument to the function
Fixed broken function call by adding missing required argument
> [DAR-2239][External] Added missing argument for call of get_image_path_from_stream()

- darwin/options.py
When posting dataset item comments through the CLI, the text argument should be required. Not providing the text argument with a value causes the API request to post the comment to fail
Make the text argument required instead
Made the comment text argument required when posting dataset item comments through the CLI
> [DAR-2294][External] Made text a required argument when posting comments through CLI

- darwin/dataset/remote_dataset.py
When using `RemoteDataset.get_release()`, if the specified release cannot be found, a `NotFound` error is raised with the dataset identifier
Instead, raise the `NotFound` error with the release name
Corrected error message when trying to get a dataset release that doesn't exist
> [DAR-2275][External] Correct get_release() NotFound error

- darwin/utils/utils.py
- tests/darwin/exporter/formats/export_darwin_test.py
In [DAR-1679](https://github.com/v7labs/darwin-py/pull/823), we made darwin-py ignore the properties metadata file when trying to read annotation files to avoid a bug. We did not implement this behaviour for Windows filesystems
Update solution to include Windows filesystems
Made Windows filesystems ignore the properties metadata file when reading annotation files
> [DAR-2305][External] Ignore the properties metadata file when reading annotations on Windows filesystems

- darwin/backend_v2.py
- darwin/client.py
- darwin/dataset/remote_dataset.py
- darwin/dataset/remote_dataset_v2.py
- darwin/exporter/formats/mask.py
- darwin/importer/formats/csv_tags.py
- darwin/utils/__init__.py
- pyproject.toml
- tests/darwin/dataset/release_test.py
- tests/darwin/dataset/remote_dataset_test.py
- tests/darwin/dataset/split_manager_test.py
- tests/darwin/exporter/formats/export_mask_test.py
- tests/darwin/importer/formats/import_nifti_test.py
We use [ruff](https://docs.astral.sh/ruff/) to lint darwin-py. There've been some long standing non-functional errors highlighted by the linter
Resolve the errors worth resolving, and suppress those that are not 
Fixed or suppressed remaining darwin-py errors highlighted by the ruff linter
> [DAR-2487][External] Fixed long-standing ruff linter issues

- .github/workflows/EVENT_merge_to_master.yml
- .github/workflows/EVENT_release.yml
- .github/workflows/JOB_check-master-can-release.yml
- .github/workflows/JOB_e2e.yml
Reverts v7labs/darwin-py#821
github-script V3 -> V7 introduced significantly breaking changes we can't test outside of the master branch. There are no benefits to upgrading at this stage, so revert
> Revert "Bump the github-actions group with 2 updates"

- poetry.lock
- pyproject.toml
The `opencv-python-headless` package released version [4.10.0.84](https://pypi.org/project/opencv-python-headless/#history) yesterday, but it has an [issue](https://github.com/opencv/opencv-python/issues/1005) for MacOS arm64 wheels
We should pin to 4.10.0.82 until we need to change
Fixed opencv version used by darwin-py
> [DAR-2469][External] Fixed opencv version to 4.10.0.82

- poetry.lock
- pyproject.toml
In darwin-py 0.8.62, we added tenacity as a dependency for exponential backoff. The latest version (8.4.0) released this morning [broke](https://github.com/langchain-ai/langchain/issues/22972), resulting in an [issue](https://github.com/v7labs/darwin-py/issues/867) with darwin-py
We gain nothing from upgrading beyond 8.3.0, so lock tenacity to 8.3.0 until we need to upgrade
Locked tenacity to 8.3.0
> [DAR-2640][External] Lock tenacity to 8.3.0

- darwin/utils/utils.py
- tests/darwin/utils_test.py
It's not possible to create annotation class names with leading or trailing whitespaces in the Darwin platform. However, when importing annotation class names with leading or trailing whitespaces in Darwin JSON 2.0, darwin-py doesn't strip these whitespaces away. This means that when comparing the list of local classes against the list of remote classes, darwin-py treats these classes as new and tries unsuccessfully to create them. The following error is then thrown:
`darwin.exceptions.ValidationError: {'errors': {'name': ['Class of type tag with name: WEED:BROADLEAF already exists.']}}
`
This PR strips the leading and trailing whitespaces from class names when importing Darwin JSON 2.0
Strip leading and trailing whitespace characters from annotation class names upon import of Darwin JSON …
> [DAR-2606][External] Strip leading & trailing whitespaces from class names when reading Darwin JSON annotations

- darwin/importer/importer.py
When using `importer.import_annotations`, if the `use_multi_cpu` flag is set to `True`, no annotation files can be read
The problem appears to be that the multi-processed parsing attempts to use a different progress bar to display progress. If we make it use the same progress bar (tqdm) as the single CPU case, the issue is resolved
Resolved bug with multi-processed annotation parsing
> [DAR-2110][External] Fixed multiprocessing annotation parsing issue with console

- poetry.lock
- pyproject.toml
Not pinning dependencies to major versions can introduce breaking changes
Pin dependencies to major versions
Pinned darwin-py dependencies to major versions to prevent accidentally introducing breaking changes
> [DAR-2660][External] Pinned dependency major versions

- darwin/utils/utils.py
darwin-py currently forbids the upload of `.mkv`, `.hevc`, `.qtiff` and `.rvg` files, despite being supported by the Darwin platform
Allow the upload of these filetypes
Allowed the upload of `.mkv`, `.hevc`, `.qtiff`, `.rvg` video filetypes with darwin-py
> [DAR-2739][External] Add `.mkv`, `.hevc`, `.qtiff` and `.rvg` as supported extensions

- darwin/dataset/remote_dataset_v2.py
Recently, we've encountered significant issues with our item processing queues being overloaded. Part of our strategy to mitigate this is to introduce rate limiting for the registration endpoints and a cap on the maximum number of items that can be registered in a single request. This PR introduces the latter for registration through darwin-py
Significantly reduce the maximum number of items that can be registered in a single request to 10
Adjusted the maximum number of items that can be registered in a single request to 10 to reduce the chance of overloading our processing queues
> [DAR-2463][External] Adjusted maximum number of items that can be registered in a single request

- darwin/cli_functions.py
- darwin/importer/importer.py
In [DAR-2347](https://github.com/v7labs/darwin-py/pull/864), we introduced optional non-scaling import & export flows for NifTI annotations. However, there we only introduced changes that allow control over the scaling behaviour of CLI-initiated annotation imports, not through the SDK, such as [this type of flow](https://docs.v7labs.com/recipes)
This PR introduces the same control in SDK-initiated annotation imports
Allow control over legacy NifTI import logic through SDK-initiated imports
> [DAR-3111][External] CLI-controllable legacy NifTI import behaviour

- Dockerfile
- Dockerfile.develop
There have historically been many requests to use darwin-py as cloud infrastructure. These have been tricky to support due to build dependencies in darwin-py
This PR allows darwin-py to be deployed easily on a container, removing the difficulties of build dependencies
Added `Dockerfile` for darwin-py
> [DAR-3424][Externa] Added `Dockerfile`

- darwin/importer/importer.py
- tests/darwin/importer/importer_test.py
Version 1.0.4 introduced a bug with the annotation importer that causes it to fail with a syntax error if `append=False`, which is the default behaviour
The root cause is that 1.0.4 changed the structure of the `remote_files` object to work with annotation & slot alignment, but this broke the overwrite warning checker, which was expecting the old structure
To resolve, this PR updates the structure that the overwrite warning checker expects
Resolved bug with importing annotations when not appending
> [DAR-3430][External] Fixed annotation import issue with changed `remote_files` structure

- .github/workflows/EVENT_release.yml
- .github/workflows/JOB_e2e.yml
- darwin/importer/importer.py
We've recently had a couple annotation import bugs that would have been caught by E2E tests. However:
- The Slack bot we have configured to notify us of failing nightly E2Es is broken
- Passing E2Es are not a requirement to release new darwin-py versions
This PR:
- 1: Fixes the Slack bot that notifies us when nightly E2E runs fail
- 2: Introduces an E2E test run that needs to pass during the release process for it to succeed
Introduced a requirement for E2E tests to pass before new darwin-py versions can be released
> [DAR-3431][External] Adding passing E2E tests as a requirement to release

- .github/CODEOWNERS
- .github/workflows/EVENT_release.yml
- .github/workflows/JOB_e2e.yml
- .github/workflows/JOB_tests.yml
- docs/release_process.md
Currently, we use static user credentials for PyPi to release new darwin-py versions. Ideally, static credentials should not be used
This PR adjusts the release process to authenticate with PyPi via OIDC, which uses short-lived tokens. This guide was followed: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi 
Removed the need for static credentials when publishing versions of darwin-py
> OIDC-based releases

- .github/workflows/EVENT_tag.yml
`EVENT_tag.yml` needs `write` permission to create releases, but it only has `read` permissions
Grant it `write` permissions instead
> Granted write access to EVENT_tag so it can create releases

- .github/workflows/EVENT_merge_to_master.yml
- .github/workflows/EVENT_pull_request.yml
- .github/workflows/EVENT_release.yml
- .github/workflows/EVENT_tag.yml
- .github/workflows/EVENT_update-linear-labels.yml
- .github/workflows/JOB_check-master-can-release.yml
- .github/workflows/JOB_e2e.yml
- .github/workflows/JOB_lint.yml
- .github/workflows/JOB_typecheck.yml
- darwin/exporter/formats/nifti.py
- darwin/future/data_objects/dataset.py
- darwin/future/data_objects/release.py
- darwin/future/data_objects/sorting.py
- darwin/future/data_objects/team.py
- darwin/importer/formats/nifti.py
- deploy/_filter_files.py
- poetry.lock
- pyproject.toml
Upgrade versions of `torch` & `torchvision` used and restrict GITHUB_TOKEN access
> [DAR-3487][External] Mitigate security issues found by CodeQL

- darwin/importer/importer.py
- tests/darwin/importer/importer_test.py
Work introduced in darwin-py 1.0.4 introduced a bug when importing NifTI annotations in the using the legacy method. When doing this, we turn the importer into a partial function. In 1.0.4 we introduced a function that checks the format of the importer. However, it does not work with partial functions, resulting in:
```
Traceback (most recent call last):   File "test.py", line 12, in <module>     importer.import_annotations(dataset, parser, ANNOTATION_PATHS, append=True)   File "/Users/john/Documents/code/development/darwin-py/darwin/importer/importer.py", line 851, in import_annotations     annotation_format = _get_annotation_format(importer)   File "/Users/john/Documents/code/development/darwin-py/darwin/importer/importer.py", line 1521, in _get_annotation_format     return …
```
> [DAR-3579][External] Resolved legacy NifTI annotation import blocker

- darwin/dataset/remote_dataset.py
- darwin/importer/importer.py
- tests/darwin/dataset/remote_dataset_test.py
When importing annotations, if any class needs to be created or assigned to the target dataset (not just masks), no raster layer annotations are actually imported
This is because if this happens, we create / update the classes as needed, then we re-fetch them [here](https://github.com/v7labs/darwin-py/blob/ad35478030eb7bc501a72a1beba84620a61c52ee/darwin/importer/importer.py#L931)
The problem is when we re-fetch the classes, we only fetch classes assigned to the dataset with `dataset.fetch_remote_classes()`
[Previously we were looking at team-wide classes](https://github.com/v7labs/darwin-py/blob/ad35478030eb7bc501a72a1beba84620a61c52ee/darwin/importer/importer.py#L791) with `dataset.fetch_remote_classes(team_wide=True)`. It seems that the ` __raster_layer__` class is never assigned to any …
> [DAR-3333][External] Import raster layer annotations even if classes are created or updated

- darwin/dataset/utils.py
During model training (and inference), for files whose pixels do not correspond to their EXIF rotation metadata, the images are loaded without adjusting according to this metadata.
During training (and inference) apply the orientation if present.
In Torch Dataloaders, reorient images according to EXIF rotation metadata if present.
> [DAR-3695][External] Handle exif data when loading images during training

- darwin/datatypes.py
- darwin/future/data_objects/properties.py
- darwin/future/tests/core/fixtures.py
- darwin/importer/importer.py
- darwin/torch/transforms.py
- darwin/utils/utils.py
- tests/darwin/client_test.py
- tests/darwin/data/metadata_missing_annotation_property_values.json
- tests/darwin/data/metadata_missing_section_property_values.json
- tests/darwin/importer/importer_test.py
darwin-py is currently incapable of handling:
- 1: A per-property `granularity` field in the `.v7/metadata.json` properties manifest file
- 2: `frame_index=null` values for annotation-level property values
Both concepts must be supported by darwin-py to allow the same import functionality as section-level properties (which are currently supported properties)
- Extend the `Property` class with `granularity`
- Introduce the `PropertyGranularity` enum to represent the 3 property granularities
Adjusted the properties import functions to ensure :
1. Annotation-level property values can be imported, but that `granularity` is optional so that section-level property values can still be imported
2. Annotation-level property values present in the properties manifest but that are missing in the team …
> [DAR-3771][External] Import of annotation-level properties

- darwin/future/core/client.py
Whenever darwin-py makes an API call, it raises various exceptions in the `raise_for_darwin_exception()` function if the `response` object has an error code that needs to be raised. However, it simply raises the object itself which shows only the error code. It would be very helpful (especially for 422s) if the error text was also displayed
Display `response.text` as well as `response` when raising HTTP error codes
Increased detail of error handling in darwin-py
> [DAR-3984][External] Improved HTTP error code verbosity

- darwin/importer/importer.py
- tests/darwin/data/metadata_identical_properties_different_classes.json
- tests/darwin/importer/importer_test.py
This PR address an issue that occurs when creating two identically named properties on separate classes **and** then importing values of those properties in the same import action. In this scenario, we get this type of error:
```
Errors importing 000000580635.jpg
{'errors': {'annotations': [{}, {}, {}, {}, {'annotation_properties': ["index '0', property 'bc5b7760-7786-4a0c-af89-8fdace15a0bf': property is not linked to the annotation's class"]}, {'annotation_properties': ["index '0', 
property 'bc5b7760-7786-4a0c-af89-8fdace15a0bf': property is not linked to the annotation's class"]}]}}
```
However: The import does successfully create the properties & their values. Additionally, a 2nd import will import the annotations without error
The problem is that the `annotation_property_map` …
> [DAR-3920][External] Bug fix for importing property values to identically named properties during property creation

- darwin/dataset/upload_manager.py
- tests/darwin/cli_functions_test.py
- tests/darwin/dataset/remote_dataset_test.py
- tests/darwin/dataset/upload_manager_test.py
- tests/fixtures.py
Recently, I discovered that it's possible to add slots to existing items. The ability to upload multi-file items with `push` was built on the assumption that this was impossible, and has led to the following behaviour (because we name slots differently based on the merge mode):
1: Upload some files as one merge mode --> No error
2: Upload the same files a different merge mode --> No error
3: Upload the same files as the same merge mode as step 2 again --> You get an error about skipping files
We've decided that this type of scenario should be blocked in darwin-py, as most users would expect deduplication validation to take place on the item-name level
Add a function to the `UploadHandler` constructor that runs the following before beginning the upload:
- 1: Gets a full list of full remote …
> [DAR-3846][External] Prevent upload of dataset items where the `{item_path}/{item_name}` already exists in the dataset

- darwin/importer/importer.py
darwin-py 1.0.9 introduced the ability to import item-level properties. Unfortunately, the item-level properties importer was written in a way that breaks the import flow of other formats with this error:
```
Importing annotations from local file:   0%|                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
Processing local annotation files:   0%|                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
File "test.py", line 13, in <module>
importer.import_annotations(dataset, …
```
> [DAR-4298][External] Skip item-properties import for non-Darwin JSON 2.0 formats

- e2e_tests/cli/test_import.py
- e2e_tests/data/import/video_annotations_with_subtypes/mini_uct.json
- e2e_tests/data/import/video_annotations_without_subtypes/mini_uct.json
- e2e_tests/helpers.py
- e2e_tests/objects.py
No E2E tests for importing annotations to video files
Modifies E2E helper functions to handle video files, then:
Adds 2 E2E annotation import tests to `e2e_tests/cli/test_import.py`
- `test_import_basic_annotations_to_videos` - Test importing a set of basic video annotations (no sub-types or properties) to a set of pre-registered files in a dataset
- ` test_import_annotations_with_subtypes_to_videos` - Test importing a set of video annotations including  subtypes & properties to a set of pre-registered files in a dataset
Improved test coverage for importing annotations to videos
> [DAR-4037] E2E tests for importing annotations to videos

- darwin/importer/importer.py
- e2e_tests/cli/test_import.py
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_1.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_2.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_3.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_4.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_5.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_6.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_7.json
- e2e_tests/data/import/image_annotations_item_level_properties_no_annotations/image_8.json
When importing annotations to items in Darwin JSON 2.0, item-level property values are ignored if there are no annotations. This happens because before item-level properties, all properties were tied to annotations, so it made sense to skip import in these cases
However, item-level properties are independent of annotations and so should be able to be imported independently
Do not skip annotation files for import if they contain item-level properties but no annotations
Allow import of item-level properties without annotations
> [DAR-4489][External] Import item-level properties without annotations

- darwin/future/data_objects/properties.py
- darwin/importer/importer.py
- darwin/path_utils.py
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_1.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_2.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_3.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_4.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_5.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_6.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_7.json
- e2e_tests/data/import/image_annotations_with_item_level_properties/image_8.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/.v7/metadata.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_1.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_2.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_3.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_4.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_5.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_6.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_7.json
- e2e_tests/data/import/image_new_annotations_with_item_level_properties/image_8.json
- e2e_tests/setup_tests.py
- tests/darwin/importer/importer_test.py
darwin-py does not have the ability to:
- Create missing text-item level properties from the properties manifest file
- Import text item-property values
- Add the above capabilities
- We also remove the ability to create any property (`item`, `annotation`, or `section`) from annotations alone. Properties may only be created from the manifest file, since otherwise we'd need to make an assumption about what type of property we are creating
Import of text item-level properties
> [DAR-2973][External] Creation and import of text item-level properties

- e2e_tests/cli/test_import.py
- e2e_tests/cli/test_pull.py
- e2e_tests/helpers.py
No E2E test for `pull`
Add an E2E test for `pull`
Improved E2E test coverage
> [DAR-4040][External] E2E test for `pull`

- darwin/dataset/remote_dataset_v2.py
- tests/darwin/dataset/remote_dataset_test.py
Items in the root of a folder being pushed are currently uploaded to a `.` folder, instead of the actual dataset root itself
When uploading files while preserving the local directory structure, place items in the root of target directories into the dataset root instead of a `.` directory
Fixed minor bug when uploading files to the root of a dataset folder when preserving the local directory structure
> [DAR-4137][External] Do not push files in root of pushed directories to a `.` directory when `preserve_folders=True`

- darwin/cli.py
- darwin/cli_functions.py
- darwin/dataset/remote_dataset_v2.py
- darwin/dataset/upload_manager.py
- darwin/options.py
- tests/darwin/cli_functions_test.py
- tests/darwin/dataset/upload_manager_test.py
Our upload APIs expose a `handle_as_slices` option, which forces each input DICOM file to be treated as a single slice rather than a volume
darwin-py does not currently expose this, but it should
Add `handle_as_slices` as a CLI & SDK `push` option
Allow users to force DICOM files to be uploaded as slices when uploading via darwin-py
> [DAR-4878][External] Addition of the `handle_as_slices` argument for `push`

- .github/workflows/JOB_e2e.yml
- .github/workflows/JOB_format.yml
- .github/workflows/JOB_generate_documentation.yml
- .github/workflows/JOB_lint.yml
- .github/workflows/JOB_tests.yml
- .github/workflows/JOB_typecheck.yml
- README.md
- darwin/importer/importer.py
- deploy/check_python.sh
- docs/DEV.md
- e2e_tests/cli/test_import.py
- poetry.lock
- pyproject.toml
- tests/darwin/dataset/upload_manager_test.py
- tests/darwin/importer/importer_test.py
Python 3.8 is now end-of-life and will no longer receive security updates
This PR:
- Drops support for Python 3.8
- Adds support for Python 3.12
- Drop support for Python 3.8
- Add support for Python 3.12
> [DAR-3444][External] Drop support for Python 3.8 & add support for Python 3.12

- .github/workflows/EVENT_release.yml
- .github/workflows/JOB_generate_documentation.yml
Since including support for Python 3.12 in master, Ubuntu GH runners that need to install all darwin-py dependencies have started OOMing
Remove unnecessary files from Ubuntu GH runners that require the space
Fixed an out-of-memory issue in darwin-py's GitHub CI
> [DAR-4923][External] Grant more memory to Ubuntu GH runners that need it

- darwin/exporter/formats/coco.py
- e2e_tests/data/convert/coco/from/base_annotation.json
- e2e_tests/data/convert/coco/to/output.json
- tests/darwin/exporter/formats/export_coco_test.py
In [this section](https://github.com/v7labs/darwin-py/commit/973d9cc7b87b1b001c42c5a0726c19000d03f8bb#diff-1ce0353c6b56373ab8cacc1aede1e66dbe5470136d11e76597b7e93f36895fd2L525-L552) of PLA-585, we removed the coco exporter's ability to export complex polygons. This was done by mistake as part of removing V1 code
Re-add the logic for converting complex polygons. In the [COCO format](https://cocodataset.org/#format-data):
- Simple polygons (`iscrowd=0`) are represented as series of `(x, y)` points
- Complex polygons (`iscrowd=1`) are represented with RLE
Also updated existing unit & E2E tests for converting to COCO to include complex polygons
Fixed regression affecting conversion of complex polygons to the COCO format
> [DAR-4931][External] Fixed regression affecting converting complex polygons to coco

- darwin/dataset/remote_dataset_v2.py
- darwin/importer/importer.py
- tests/darwin/importer/importer_test.py
This ticket tackles 2 problems:
- 1: When importing annotations to items not ready to receive them, imports would fail without any error handling. These are items in the `uploading`, `processing`, `error`, and `archived` statuses
- 2: When importing `NifTI` annotations, if any item in the dataset was not in a state to receive annotations (even an item not targeted by the import), the import would fail without any error handling. This is happening due to the `fetch_remote_files()` call in `_get_remote_files_that_require_legacy_scaling()` not filtering for item status, then trying to retrieve slot information
- 1: If an import job is trying to import annotations to item(s) not ready to receive them, we raise an error and display which items are affected and what statuses they are in
- 2: …
> [DAR-5014][External] Better error messaging when importing to items not ready to receive annotations

- darwin/dataset/upload_manager.py
- tests/darwin/dataset/upload_manager_test.py
This validation logic introduced in DAR-3846 only covers a very rare edge case, and makes very expensive API calls for every `push` operation
We remove this validation and may re-introduce this validation on the backend in the future
Removed expensive pre-`push` validation from darwin-py that provided a negligible benefit
> [DAR-5293][External] Removed `{item_path}/{item_name}` validation on `push`

- .github/workflows/EVENT_merge_to_master.yml
We recently updated `github-script` from version 3.2.0 to 7.0.1. This update uses slightly different syntax
Update syntax of `createCommitStatus` used in the merge to master event
Maintenance of CI pipeline
> [DAR-5340][External] Update `github-script` syntax

- darwin/importer/formats/coco.py
- tests/darwin/importer/formats/import_coco_test.py
COCO segmentations can have >1 polygon (an array of arrays containing `x, y`). Currently we only select the first element
Allow import of multiple segmentation array elements as a single polygon. This effectively adds support for importing complex polygons
Allowed import of multi-array COCO segmentations
> [DAR-5342][External] Allow import of complex polygons in `COCO`

- darwin/cli_functions.py
- darwin/dataset/remote_dataset.py
- darwin/dataset/remote_dataset_v2.py
- docs/DEV.md
- tests/darwin/cli_functions_test.py
This PR contains 2 cleanup commits that were to go out with now cancelled tickets:
- [Replace Iterator with Iterable for better flexibility](https://github.com/v7labs/darwin-py/pull/990/commits/10d1b3c9624e61704ea1b660d9db86bfa6811c7e)
- [Removed deprecated dataset.reset method](https://github.com/v7labs/darwin-py/pull/990/commits/ef8061581cdeb16be96c17606272fa25994a6ad2)
It also adds information on linting and formatting to `DEV.md`
Improved type flexibility of dataset methods and removed deprecated V1 function
> 3 small cleanup changes

- .github/workflows/version_bump.yml
Automatically create a PR with the version bump and a draft release
> Version bump update

- deploy/increase_version.py
`--minor` flag didn't reset `patch` version. `--major` flag didn't reset `minor` and `patch`
`--minor` flag resets `patch` to zero
`--major` flag resets `minor` and `patch` to zero
Fix increase version for --minor and --major flags by properly resetting lower version numbers to zero
> Fix increase version for --minor and --major flags 

- .github/workflows/version_bump.yml
> Update version pull req

- poetry.lock
- pyproject.toml
See this [issue](https://github.com/v7labs/darwin-py/issues/1044) for more info
Upgraded the version directly in the pyproject.toml file
argcomplete is now "^3.5.0"
> DAR-6458 [external]: upgraded argcomplete to 3.6.2

- poetry.lock
- pyproject.toml
Reverts v7labs/darwin-py#1046 because it breaks the master build
> Revert "DAR-6458 [external]: upgraded argcomplete to 3.6.2"

- darwin/cli.py
- darwin/cli_functions.py
- darwin/client.py
- darwin/datatypes.py
- darwin/options.py
- tests/darwin/cli_functions_test.py
- tests/darwin/client_test.py
It is impossible to query V3 annotator reports using the SDK. Reports V1 can be queried, but are not created since 11/05/2024.
Add a new top-level command and an action for V3 annotator reports: `darwin report annotators`.
Instead of requesting an annotator report synchronously, start a report job, and poll for results with exponential backoff. For now, log the id of the created job and raise an error if the happy path fails.
Added top-level `report` command, added `report annotators` command to query V3 annotator reports
> [DAR-6195][external] Support Reports v3 in Darwin Py

- darwin/datatypes.py
Type annotaitons like `str | None` are not supported for python 3.9. Darwin v1.3.0 can't be used
Change annotation to `Optional[str]`
Fix type annotaiton, use `Optional`
> Fix type annotation

- darwin/cli_functions.py
- darwin/torch/dataset.py
- darwin/torch/utils.py
`offline` parameter in `_load_client` function is unused.
Drop the parameter from all calls, function definition and docstring. This function is marked as internal, and hopefully not used by SDK users.
drop unused `offline` parameter from `cli_functions._load_client()`
> [internal] Remove unused offline param from _load_client

- .github/workflows/EVENT_merge_to_master.yml
- .github/workflows/JOB_tests.yml
1. We must avoid being notified of a failure late after the code is merged.
2. We must avoid being notified about an e2e failure only after the nightly run
3. If multiple PRs are merged to master only the last one runs the full GHA 
1. Run unit tests for each PR (Ideally we'd run e2e but curretly it takes 45min so not worth it)
2. Run e2e for each merge to master
3. Remove concurrency so that each commit to master gets its own full run. This is important cause in case of multiple PRs we can quickly identify which commit is responsible of a failure (otherwise we wouldn't know what introduced a failure and we'd need to revert them all)
> [internal] Shift left testing

- darwin/exporter/formats/nifti.py
Export to nifti volumes has a large memory footprint. We encountered out of memory errors during export.
Each exported nifti volume is casted to int16 to be written to disk, moreover, each volume we export has just one mask. Thus we can use `np.uint8` datatype for volumes during export processing to save space.
Use np.uint8 as datatype for output nifti volumes to reduce allocations
> [DAR-6557][Internal] Use np.uint8 as datatype for output nifti volumes to reduce allocations

- darwin/datatypes.py
- darwin/utils/utils.py
- tests/darwin/datatypes_test.py
- tests/darwin/importer/importer_test.py
In [DAR-5605](https://github.com/v7labs/darwin-py/pull/993) we started properly handling the case when attributes are unset during import, by passing an empty list of attributes in the payload for the unset frame.
In [DAR-5903](https://github.com/v7labs/darwin-py/pull/1005/files) we made sure unsetting attributes by passing an empty list happened only to keyframes, not to all frames.
The remaining problem is:
- we have keyframes 1 and 3, 4 where the annotation changes.
- we have key subframes 2 and 3, where the attributes change.
- during export we don't differentiate between frames and subframes, and end up getting key frames 1, 2, 3, 4.
- on re-import we create *both* keyframes and key subframes 1, 2, 3, 4.
```
--- Original item
key frames: 1 _ 3 4
key sub-frames: _ 2 3 _
--- Exported …
```
> [DAR-6533][External] Do not store duplicate attributes in keyframes

- .github/workflows/JOB_e2e.yml
- Run at 3am so that results are ready before releases
- Given we've added trigger runs from backend staging releases https://github.com/v7labs/darwin-backend/pull/5778 I've also added concurrency checks to avoid overlapping runs
> [DAR-6861] Update E2E workflow schedule
